/* SHEIN BI V2 preview client. Runtime data source: cloud BI section API. */
(function clientApp(){const CFG=window.__SHEIN_STORE_CONFIG__||{stores:[],ownerGroups:[]};
const TABS=[['home','总控驾驶舱','home'],['orders','订单中心','order'],['returns','退货退款','return'],['products','商品列表','product'],['inventory','库存管理','stock'],['traffic','流量数据','traffic'],['reviews','商品评价','review'],['marketing','营销中心','mkt'],['ops','自动化运营','ops'],['system','系统健康','sys']];
const SL={homeRankings:'首页销售/排行',homeProfit:'首页利润',rankings:'完整排行',profit:'利润明细',actions:'动作池',linksData:'链接/覆盖',productTrafficDaily:'货号级每日流量',inventoryTrend:'库存趋势',comments:'评价',orders:'订单',afterSales:'售后',financeData:'财务'};
const BASE_NEED={home:['homeRankings','afterSales','homeProfit','productTrafficDaily','financeData'],orders:['orders','homeRankings'],returns:['afterSales','orders','homeRankings'],products:['linksData','homeRankings'],inventory:['inventoryTrend','linksData'],traffic:['productTrafficDaily','linksData'],reviews:['comments'],marketing:['linksData','actions','financeData'],ops:['actions','linksData'],system:[]};
const NEED=BASE_NEED;
const S={tab:'home',q:'',scope:'ALL',start:'',end:'',rangePreset:'today',rangeOpen:false,calendarStartMonth:'',calendarEndMonth:'',trendMetric:'sales',salesMode:'net',qtyMode:'net',returnsMode:'request',profitMode:'loss',metric:'sales',orderPage:1,orderPageSize:80,orderStatus:'all',returnPage:1,returnPageSize:80,returnStatus:'all',returnReason:'all',returnRtv:'all',core:'idle',err:''},D={},SS={},P={};
const RMB_RATE=1.8;
const $=id=>document.getElementById(id);
const H=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const N=v=>{const n=Number(v??0);return Number.isFinite(n)?n:0};
const M=v=>N(v).toLocaleString('zh-CN',{maximumFractionDigits:0});
const M2=v=>N(v).toLocaleString('zh-CN',{maximumFractionDigits:2});
const PCT=v=>(v==null||v===''||!Number.isFinite(Number(v)))?'—':(Number(v)*100).toFixed(1)+'%';
const A=v=>Array.isArray(v)?v:[];
const ISO=v=>String(v||'').slice(0,10);
const pad2=v=>String(v).padStart(2,'0');
function parseDateOnly(v){const m=String(v||'').slice(0,10).match(/^(\d{4})-(\d{2})-(\d{2})$/);return m?new Date(Number(m[1]),Number(m[2])-1,Number(m[3])):null}
function isoDate(d){return d instanceof Date&&!Number.isNaN(d.getTime())?`${d.getFullYear()}-${pad2(d.getMonth()+1)}-${pad2(d.getDate())}`:''}
function addDateDays(dateText,days){const d=parseDateOnly(dateText)||new Date();d.setDate(d.getDate()+Number(days||0));return isoDate(d)}
function monthStart(dateText){const d=parseDateOnly(dateText)||new Date();return isoDate(new Date(d.getFullYear(),d.getMonth(),1))}
function addMonths(dateText,months){const d=parseDateOnly(monthStart(dateText))||new Date();return isoDate(new Date(d.getFullYear(),d.getMonth()+Number(months||0),1))}
function monthEnd(dateText){const d=parseDateOnly(monthStart(dateText))||new Date();return isoDate(new Date(d.getFullYear(),d.getMonth()+1,0))}
function monthId(v){return String(v||'').slice(0,7)}
function fmtStamp(v){if(!v)return'—';const d=new Date(v);return Number.isNaN(d.getTime())?String(v).slice(0,19):d.toLocaleString('zh-CN',{hour12:false})}
function shortDate(v){return String(v||'').slice(0,10)||'—'}
const stores=A(CFG.stores).filter(s=>s&&s.enabled!==false&&s.storeKey).map(s=>String(s.storeKey).toUpperCase());
const smeta=new Map(A(CFG.stores).map(s=>[String(s.storeKey||'').toUpperCase(),s]));
const owners=A(CFG.ownerGroups).map(g=>({...g,key:String(g.key||g.name||'').toUpperCase(),stores:A(g.stores).map(x=>String(x).toUpperCase())}));
const ownByStore=new Map();owners.forEach(g=>g.stores.forEach(s=>ownByStore.set(s,g)));
function ownerStoresLabel(g){return A(g?.stores).filter(Boolean).join('/')}
function ownerOptionLabel(g){const ss=ownerStoresLabel(g);return `负责人 · ${g?.name||g?.key||''}${ss?'（'+ss+'）':''}`}
function arrp(p){return p.split('.').reduce((o,k)=>o?.[k],D)||[]}

function prod(r){const key=String(r?.standard_goods_sn||r?.goods_sn||r?.raw_goods_sn||'').trim();const names=D.productDisplayNames&&typeof D.productDisplayNames==='object'?D.productDisplayNames:{};return String((key&&names[key])||r?.product_display_name||r?.standard_goods_sn||r?.goods_sn||r?.raw_goods_sn||r?.goods_title||'-')}

function pkey(r){return String(r?.standard_goods_sn||r?.goods_sn||r?.raw_goods_sn||prod(r)||'').trim()}

function sk(r){return String(r?.store_key||r?.storeKey||'').trim().toUpperCase()}

function dt(r){return ISO(r?.date||r?.stat_date||r?.created_date||r?.order_created_date||r?.link_date||r?.snapshot_date||r?.comment_date||r?.request_time||r?.order_create_time||r?.order_time||r?.created_at)}

function scopeStores(){const s=String(S.scope||'ALL');if(s==='ALL')return new Set(stores);if(s.startsWith('OWNER:'))return new Set((owners.find(g=>g.key===s.slice(6).toUpperCase())?.stores)||[]);return new Set([s.toUpperCase()])}

function scopeName(){const s=String(S.scope||'ALL');if(s==='ALL')return'全部店铺';if(s.startsWith('OWNER:'))return owners.find(g=>g.key===s.slice(6).toUpperCase())?.name||s;return `${s} · ${(smeta.get(s)?.companyName)||''}`}
function storeDisplayName(key){const s=String(key||'').trim().toUpperCase();const name=String(smeta.get(s)?.companyName||'').trim();return name?`${s} · ${name}`:s}

function ok(r){const d=dt(r);if(d&&S.start&&d<S.start)return false;if(d&&S.end&&d>S.end)return false;
const st=sk(r);if(st&&!scopeStores().has(st))return false;if(!st&&S.scope!=='ALL')return false;
const q=String(S.q||'').trim().toLowerCase();if(q){const short=/^[a-z0-9-]{1,4}$/i.test(q);
const itemText=A(r?.items).map(it=>[it?.standard_goods_sn,it?.skc,it?.goods_title,it?.order_status_group].filter(Boolean).join(' ')).join(' ');
const productSearch=[pkey(r),prod(r),r?.goods_title,r?.skc,r?.sku,r?.product_summary,r?.product_detail_summary,r?.product_search_text,itemText];
const fields=short?productSearch:[...productSearch,r?.search_text,r?.bill_no,r?.order_no,r?.return_order_no,r?.aftersales_order_no,r?.express_no,r?.express_code,r?.et_outbound_id];
const hay=fields.map(x=>String(x||'').toLowerCase()).join('|');if(!hay.includes(q))return false}return true}

function F(rows){return A(rows).filter(ok)}

function sum(rows,fs){return rows.reduce((a,r)=>a+fs.reduce((x,f)=>x+N(r?.[f]),0),0)}

function firstNum(r,fs){for(const f of fs){if(Object.prototype.hasOwnProperty.call(r||{},f)&&r?.[f]!=null&&r?.[f]!=='')return N(r[f])}return 0}

function sumFirst(rows,fs){return rows.reduce((a,r)=>a+firstNum(r,fs),0)}

function grp(rows,fn){const m=new Map();for(const r of A(rows)){const k=fn(r);if(!k)continue;if(!m.has(k))m.set(k,[]);m.get(k).push(r)}return m}

function uniq(xs){return Array.from(new Set(xs.filter(Boolean)))}

function avg(rows){const rev=sumFirst(rows,['sales_sar','net_revenue_sar']),q=sum(rows,['quantity']);return q?rev/q:0}

function merge(x){if(!x||typeof x!=='object')return;Object.assign(D,x.data&&typeof x.data==='object'?x.data:x);if(x.generatedAt&&!D.__latestSectionGeneratedAt)D.__latestSectionGeneratedAt=x.generatedAt}

function genAt(){return D.__sections?.generatedAt||D.generatedAt||D.__latestSectionGeneratedAt||''}

function homeNeeds(){const ns=new Set(BASE_NEED.home);if(S.q||S.trendMetric==='profit')ns.add('profit');if(S.trendMetric==='inventory')ns.add('inventoryTrend');return Array.from(ns)}
function needsFor(tab=S.tab){return tab==='home'?homeNeeds():(BASE_NEED[tab]||[])}
function surl(n){return (location.protocol==='http:'||location.protocol==='https:')?'/api/bi/section/'+encodeURIComponent(n):'../sections/'+encodeURIComponent(n)+'.json'}async function core(){S.core='loading';render();try{const r=await fetch('../data.json?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error('core HTTP '+r.status);merge(await r.json());S.core='ok';S.err='';dates(true);render();ensure(S.tab,true)}catch(e){S.core='error';S.err=e?.message||String(e);render()}}async function load(n,silent=false,force=false){if(SS[n]?.status==='ok'&&!force)return true;if(SS[n]?.status==='error'&&!force)return false;if(P[n])return P[n];SS[n]={status:'loading',error:''};if(!silent)render();P[n]=fetch(surl(n),{cache:'no-store'}).then(async r=>{if(!r.ok)throw Error('HTTP '+r.status);
const j=await r.json();if(j&&j.ok===false)throw Error(j.error||'section failed');const expected=D.__sections?.generatedAt||D.generatedAt||'';if(expected&&j.generatedAt&&j.generatedAt!==expected)throw Error(n+' generatedAt 不匹配：section='+j.generatedAt+' core='+expected);merge(j);dates(false);SS[n]={status:'ok',error:'',generatedAt:j.generatedAt||''};delete P[n];render();return true}).catch(e=>{SS[n]={status:'error',error:e?.message||String(e)};delete P[n];render();return false});return P[n]}

function ensure(tab=S.tab,silent=false){needsFor(tab).forEach(n=>load(n,silent))}

function chips(ns){return'<div class="sects">'+(ns||[]).map(n=>{const s=SS[n]?.status||'idle',c=s==='ok'?'ok':s==='loading'?'loading-chip':s==='error'?'bad':'';return`<span class="${c}" title="${H(SS[n]?.error||'')}">${H(SL[n]||n)} · ${s==='ok'?'已就绪':s==='loading'?'加载中':s==='error'?'失败':'待加载'}</span>`}).join('')+'</div>'}

function wait(n,t='正在从云端 section API 加载数据…'){const s=SS[n]||{};if(s.status==='error')return`<div class="error"><b>${H(SL[n]||n)} 加载失败</b><br>${H(s.error)}<p><button class="btn" data-load="${H(n)}">重试</button></p></div>`;load(n,true);return`<div class="loading"><span class="spin"></span><span>${H(t)}</span></div>`}

function collectDates(){const ds=[];
[D.dates?.salesDate,D.dates?.businessDate,D.dates?.linkDate].forEach(v=>{const d=ISO(v);if(d)ds.push(d)});
[...A(D.rankings?.dailyStores),...A(D.rankings?.dailyStoreProducts),...A(D.rankings?.dailyProducts),...A(D.homeProfitSummary?.dailyScopes),...A(D.profit?.dailyStoreProducts),...A(D.afterSales),...A(D.orders),...A(D.productTrafficDaily),...A(D.inventoryTrend),...A(D.inventoryDepletion?.visibleTrend)].forEach(r=>{const d=dt(r);if(d)ds.push(d)});
return ds.filter(Boolean).sort()}

function dataAnchorDate(){return collectDates().at(-1)||ISO(new Date().toISOString())}

function computePresetRange(key,anchor=dataAnchorDate()){const a=ISO(anchor)||ISO(new Date().toISOString());const m=monthStart(a);switch(String(key||'today')){case'yesterday':return{start:addDateDays(a,-1),end:addDateDays(a,-1)};case'last3':return{start:addDateDays(a,-2),end:a};case'last7':return{start:addDateDays(a,-6),end:a};case'last15':return{start:addDateDays(a,-14),end:a};case'last30':return{start:addDateDays(a,-29),end:a};case'thisMonth':return{start:m,end:a};case'lastMonth':{const s=addMonths(m,-1);return{start:s,end:monthEnd(s)}}case'last3Months':return{start:addMonths(m,-2),end:a};case'lastYear':return{start:addDateDays(a,-364),end:a};case'today':default:return{start:a,end:a}}}

function calendarMonthStart(dateText){return monthStart(dateText||dataAnchorDate())}
function addCalendarMonths(dateText,months){return addMonths(dateText||dataAnchorDate(),months)}
function monthTitle(dateText){const d=parseDateOnly(dateText)||new Date();return `${d.getFullYear()} 年 ${d.getMonth()+1} 月`}
function selectedRangeText(){dates(false);return S.start===S.end?S.start:`${S.start} ~ ${S.end}`}
function applyPreset(key){const r=computePresetRange(key,dataAnchorDate());S.rangePreset=key;S.start=r.start;S.end=r.end;S.rangeOpen=false;S.calendarStartMonth=calendarMonthStart(r.start);S.calendarEndMonth=calendarMonthStart(r.end===r.start?addCalendarMonths(r.start,1):r.end)}
function dates(force=false){if(!force&&S.start&&S.end)return;applyPreset(S.rangePreset||'today')}
function preset(days){const map={1:'today',3:'last3',7:'last7',15:'last15',30:'last30',365:'lastYear'};applyPreset(map[Number(days)]||'last7');sync(false);render();ensure(S.tab,true)}

function renderCalendarPanel(monthDate,role){const first=parseDateOnly(calendarMonthStart(monthDate))||new Date();const y=first.getFullYear(),m=first.getMonth();const offset=(first.getDay()+6)%7;const gridStart=new Date(y,m,1-offset);const days=[];for(let i=0;i<42;i++){const d=new Date(gridStart.getFullYear(),gridStart.getMonth(),gridStart.getDate()+i);const iso=isoDate(d);const cls=['calendar-day',d.getMonth()===m?'':'out',iso>=S.start&&iso<=S.end?'in-range':'',iso===S.start?'start':'',iso===S.end?'end':''].filter(Boolean).join(' ');days.push(`<button type="button" class="${cls}" data-calendar-date="${H(iso)}" data-calendar-role="${H(role)}">${d.getDate()}</button>`)}return `<div class="range-calendar-panel"><div class="calendar-panel-head"><div><span class="sub">${role==='start'?'开始时间':'结束时间'}</span><h4>${H(monthTitle(monthDate))}</h4></div><div class="calendar-nav"><button type="button" data-calendar-shift="${H(role)}" data-calendar-delta="-1">‹</button><button type="button" data-calendar-shift="${H(role)}" data-calendar-delta="1">›</button></div></div><div class="calendar-week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="calendar-days">${days.join('')}</div></div>`}
function rangeControl(){dates(false);if(!S.calendarStartMonth)S.calendarStartMonth=calendarMonthStart(S.start);if(!S.calendarEndMonth)S.calendarEndMonth=calendarMonthStart(S.end===S.start?addCalendarMonths(S.start,1):S.end);const presets=[['today','今天'],['yesterday','昨天'],['last3','近3天'],['last7','近7天'],['last15','近15天'],['last30','近30天'],['thisMonth','本月'],['lastMonth','上个月'],['last3Months','近3个月'],['lastYear','近一年']];const label=(presets.find(x=>x[0]===S.rangePreset)||['custom','自定义'])[1];return `<div class="range-toolbar"><div class="range-toolbar-main"><button type="button" class="range-button" data-range-toggle="1" aria-expanded="${S.rangeOpen?'true':'false'}"><span>时间筛选</span><div><strong>${H(selectedRangeText())}</strong><small>${H(label)} · 影响 KPI、趋势、排行和明细</small></div></button><div class="range-preset-strip">${presets.map(([k,l])=>`<button type="button" class="${S.rangePreset===k?'active':''}" data-range-preset="${H(k)}">${H(l)}</button>`).join('')}</div></div><div class="range-popover" ${S.rangeOpen?'':'hidden'}><div class="calendar-input-row"><label class="calendar-input-card"><span>开始日期</span><input id="rangeStart" type="text" inputmode="numeric" value="${H(S.start)}" placeholder="YYYY-MM-DD"></label><label class="calendar-input-card"><span>结束日期</span><input id="rangeEnd" type="text" inputmode="numeric" value="${H(S.end)}" placeholder="YYYY-MM-DD"></label></div><div class="range-calendar-grid">${renderCalendarPanel(S.calendarStartMonth,'start')}${renderCalendarPanel(S.calendarEndMonth,'end')}</div><div class="calendar-pick-note">左侧选开始，右侧选结束；也可以直接输入日期。快捷时间不用打开弹窗。</div></div></div>`}

function dailyStores(){return A(D.rankings?.dailyStores)}
function dailyStoreProducts(){return A(D.rankings?.dailyStoreProducts)}
function dailyProducts(){return A(D.rankings?.dailyProducts)}
function rankingProductRows(){const dsp=dailyStoreProducts();return dsp.length?dsp:dailyProducts()}
function salesBaseRows(){if(String(S.q||'').trim())return rankingProductRows();const ds=dailyStores();return ds.length?ds:rankingProductRows()}
function sales(){return F(salesBaseRows())}
function psales(){return F(rankingProductRows())}

function profits(){return F(D.profit?.dailyStoreProducts||D.profit?.dailyProducts||[])}

function orders(){return F(D.orders||[])}

function returns(){return F(D.afterSales||[]).filter(r=>String(r.order_sub_status_name||r.status||'').trim()!=='已取消')}

function actions(){return F(D.actions||[])}

function links(){return F([...A(D.storeLinks),...A(D.links)])}

function matrix(){return F(D.matrix||[])}

function traffic(){return F(D.productTrafficDaily||[])}
function trafficLooseByScope(){const q=String(S.q||'').trim().toLowerCase(),set=scopeStores(),all=S.scope==='ALL';return A(D.productTrafficDaily||[]).filter(r=>{const st=sk(r);if(st&&!set.has(st))return false;if(!st&&!all)return false;if(q){const short=/^[a-z0-9-]{1,4}$/i.test(q);const fields=short?[pkey(r),prod(r),r?.goods_title]:[pkey(r),prod(r),r?.goods_title,r?.skc,r?.sku];const hay=fields.map(x=>String(x||'').toLowerCase()).join('|');if(!hay.includes(q))return false}return true})}

function invTrend(){return F(D.inventoryTrend||D.inventoryDepletion?.visibleTrend||[])}
function invTrendLoose(){const q=String(S.q||'').trim().toLowerCase();return A(D.inventoryTrend||D.inventoryDepletion?.visibleTrend||[]).filter(r=>{const d=dt(r);if(d&&S.start&&d<S.start)return false;if(d&&S.end&&d>S.end)return false;if(q){const hay=[pkey(r),prod(r),r.goods_title].join('|').toLowerCase();if(!hay.includes(q))return false}return true})}

function invProducts(){return A(D.inventoryDepletion?.products).filter(r=>{const q=String(S.q||'').trim().toLowerCase();return !q||[pkey(r),prod(r),r.goods_title].join('|').toLowerCase().includes(q)})}

function netSales(r){return firstNum(r,['sales_sar','net_revenue_sar','known_net_revenue_sar'])}
function grossSales(r){return firstNum(r,['gross_sales_sar','gross_revenue_sar','known_gross_revenue_sar'])||netSales(r)}
function netOrders(r){return firstNum(r,['orders','valid_order_count','net_orders','order_count'])}
function grossOrders(r){return firstNum(r,['gross_orders','gross_order_count','gross_order_num'])||netOrders(r)}
function netQty(r){return firstNum(r,['quantity','net_quantity','valid_quantity','sale_cnt'])}
function grossQty(r){return firstNum(r,['gross_quantity','gross_qty','gross_sale_cnt'])||netQty(r)}
function money(v){return M2(v)+' SAR'}
function rmb(v){return M2(N(v)*RMB_RATE)+' RMB'}
function moneyCell(v){return M2(v)}
function rmbCell(v){return M2(N(v)*RMB_RATE)}
function labelNum(v,suffix=''){return Number.isFinite(Number(v))?M(v)+suffix:'—'}
function compact(v){const n=N(v),a=Math.abs(n);if(a>=100000000)return (n/100000000).toFixed(1)+'亿';if(a>=10000)return (n/10000).toFixed(1)+'万';return M(n)}
function htmlValue(v,loading=false){return loading?'<span class="pending">加载中</span>':H(v)}
function smallValue(v,loading=false){return loading?'<span class="pending">加载中</span>':`<span class="metric-note">${H(v)}</span>`}
function homeScopeSubtitle(){return `${scopeName()}${S.q?' · '+S.q:''}`}
function sourceLoading(name,rows=[]){const st=SS[name]?.status||'idle';return !rows.length&&(st==='loading'||st==='idle')}

function salesSummary(){const rows=sales();const prows=psales();const productRows=prows.length?prows:rows;const active=(fn)=>{const xs=uniq(productRows.filter(r=>fn(r)>0).map(pkey));return xs.length||null};const net=sumFirst(rows,['sales_sar','net_revenue_sar','known_net_revenue_sar']);const gross=rows.reduce((a,r)=>a+grossSales(r),0);const qty=rows.reduce((a,r)=>a+netQty(r),0);const gqty=rows.reduce((a,r)=>a+grossQty(r),0);return{rows,productRows,net,gross,ord:rows.reduce((a,r)=>a+netOrders(r),0),gord:rows.reduce((a,r)=>a+grossOrders(r),0),qty,gqty,active:active(netQty),gactive:active(grossQty),avg:qty?net/qty:0}}

function retRequestSummary(){const r=returns();return{cases:uniq(r.map(x=>x.aftersales_order_no||x.return_order_no||x.order_no||JSON.stringify(x))).length||r.length,amount:sumFirst(r,['amount_sar','price_amount_total','refund_amount_sar']),qty:sumFirst(r,['quantity','return_quantity'])||r.length,rows:r}}
function retOrderSummary(){const s=salesSummary();return{cases:Math.max(0,s.gord-s.ord),amount:Math.max(0,s.gross-s.net),qty:Math.max(0,s.gqty-s.qty)}}
function retSum(){const r=retRequestSummary();return{amt:r.amount,qty:r.qty,orders:r.cases,rows:r.rows}}

function hprofit(){const productScoped=Boolean(String(S.q||'').trim());if(productScoped)return profits();const rows=A(D.homeProfitSummary?.dailyScopes);if(!rows.length)return[];const set=scopeStores(),all=S.scope==='ALL',owner=String(S.scope).startsWith('OWNER:');return rows.filter(r=>{const d=ISO(r.date);if(S.start&&d<S.start)return false;if(S.end&&d>S.end)return false;const sv=String(r.scope_value||'').toUpperCase();if(all)return sv===''||sv==='ALL';if(owner)return set.has(sv);return sv===String(S.scope).toUpperCase()})}

function profitAmountLoss(r){return firstNum(r,['profit_after_storage_sar','profit_before_storage_sar'])}
function profitAmountRtv(r){return firstNum(r,['profit_if_rtv_received_resellable_after_storage_sar','profit_if_rtv_received_resellable_sar','profit_after_storage_sar','profit_before_storage_sar'])}
function profitRevenue(r){return firstNum(r,['net_revenue_sar','known_net_revenue_sar','gross_revenue_sar','known_gross_revenue_sar'])}
function profitStorageFee(r){const has=f=>Object.prototype.hasOwnProperty.call(r||{},f);if(has('storage_matched')&&N(r.storage_matched)<=0&&has('fallback_storage_fee_sar'))return N(r.fallback_storage_fee_sar);return firstNum(r,['storage_fee_sar','allocated_storage_fee_sar','month_storage_fee_sar','fallback_storage_fee_sar'])}
function profSum(){const hp=hprofit();return{loss:hp.reduce((a,r)=>a+profitAmountLoss(r),0),rtv:hp.reduce((a,r)=>a+profitAmountRtv(r),0),profit:hp.reduce((a,r)=>a+profitAmountLoss(r),0),revenue:hp.reduce((a,r)=>a+profitRevenue(r),0),storage:hp.reduce((a,r)=>a+profitStorageFee(r),0),src:String(S.q||'').trim()?'profit':'homeProfit',rows:hp}}

function salesSum(){const s=salesSummary();return{net:s.net,gross:s.gross,ord:s.ord,gord:s.gord,qty:s.qty,avg:s.avg,rows:s.rows}}

function trafficMetricSum(r){return firstNum(r,['eps_uv','exposure_uv','exposure_cnt','impressions'])+firstNum(r,['goods_uv','uv','visitor_cnt','visitors'])+firstNum(r,['sale_cnt','pay_order_cnt','quantity'])}
function uniqueDatesFromRows(rows){return uniq(A(rows).map(dt).filter(Boolean)).sort()}
function trafficCurrentEndingPreset(){return ['today','last3','last7','last15','last30','thisMonth','last3Months','lastYear'].includes(String(S.rangePreset||''))}
function trafficEffectiveRange(latestTrafficDate){let start=S.start,end=S.end,shifted=false;if(latestTrafficDate&&S.end&&latestTrafficDate<S.end&&trafficCurrentEndingPreset()){const r=computePresetRange(S.rangePreset,latestTrafficDate);start=r.start;end=r.end;shifted=true}return{start,end,shifted,text:start===end?start:`${start}~${end}`}}
function trafficRowsInRange(rows,start,end){return A(rows).filter(r=>{const d=dt(r);return(!d||((!start||d>=start)&&(!end||d<=end)))})}
function trafficSummary(allowLatest=true){const loose=trafficLooseByScope();const latestTrafficDate=uniqueDatesFromRows(loose).at(-1)||'';const range=trafficEffectiveRange(latestTrafficDate);const exactRows=trafficRowsInRange(loose,range.start,range.end);let rows=exactRows;let fallback=false,latestAvailable=range.shifted;const exp=sumFirst(rows,['eps_uv','exposure_uv','exposure_cnt','impressions']);const uv=sumFirst(rows,['goods_uv','uv','visitor_cnt','visitors']);const sale=sumFirst(rows,['sale_cnt','pay_order_cnt','quantity']);const latest=[...rows].sort((a,b)=>String(dt(a)).localeCompare(String(dt(b)))).at(-1)||{};const click=exp?uv/exp:firstNum(latest,['avg_click_rate','click_rate']);const pay=uv?sale/uv:firstNum(latest,['avg_pay_rate','pay_rate']);const dates=uniqueDatesFromRows(rows),nonZeroDays=uniqueDatesFromRows(rows.filter(trafficMetricSum));const prefix=range.shifted?`流量按 ${range.text}`:(dates.length?`${dates[0]}${dates.length>1?'~'+dates.at(-1):''}`:'当前范围暂无');const rangeNote=dates.length?`${prefix} · 明细${M(dates.length)}天 · 有流量${M(nonZeroDays.length)}天`:(latestTrafficDate?`${prefix} · 最新${latestTrafficDate}`:'当前范围暂无');return{rows,exactRows,exp,uv,sale,click,pay,fallback,latestAvailable,latestDate:dt(latest),latestTrafficDate,rangeNote,rangeText:range.text,effectiveStart:range.start,effectiveEnd:range.end,effectiveShifted:range.shifted,exactDateCount:uniqueDatesFromRows(exactRows).length,nonZeroDays:nonZeroDays.length}}
function inventoryScopeNote(){return S.q?'当前货号筛选；库存不按店铺/负责人拆分':'库存不按店铺/负责人拆分，仅货号搜索生效'}
function inventorySummary(){const rows=invProducts();const totalSupply=sumFirst(rows,['estimated_total_supply_quantity','total_supply_quantity']);const daily=sumFirst(rows,['weighted_daily_gross_sales','daily_sales','gross_sold_30d'])/(rows.some(r=>r.weighted_daily_gross_sales!=null)?1:30);const snap=collectDatesFromRows(rows).at(-1)||D.dates?.inventoryDate||D.dates?.etUpdatedAt||'';return{rows,count:rows.length,available:sumFirst(rows,['et_estimated_available_qty','available_qty']),onhand:sumFirst(rows,['estimated_on_hand_quantity','on_hand_quantity']),incoming:sumFirst(rows,['incoming_quantity']),totalSupply,daily,days:daily>0?totalSupply/daily:null,snapshot:snap}}
function collectDatesFromRows(rows){return A(rows).map(dt).filter(Boolean).sort()}

function intro(t,c){return`<section class="intro"><div><span class="eyebrow"><i></i>${H(t)}</span><h2>${H(t)}</h2><p>${H(c)}</p></div><div class="badge">${H(selectedRangeText())} · ${H(scopeName())}${S.q?' · '+H(S.q):''}</div></section>`}

function head(t,c,e=''){return`<div class="head"><div><h3>${H(t)}</h3><p>${H(c)}</p></div>${e}</div>`}

function cellHtml(c){const s=String(c??'');return /<(span|b|small|em|a)\b/i.test(s)?s:H(s)}
function table(headers,rows){return`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${H(h)}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${r.map((c,i)=>`<td class="${i>2?'num':''}">${cellHtml(c)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

function panel(t,sub,heads,rows){return`<section class="panel"><h4>${H(t)}</h4><p class="sub">${H(sub)}</p>${rows.length?table(heads,rows):'<div class="empty">当前筛选没有明细。</div>'}</section>`}

function trend(rows,field){const m=new Map();for(const r of rows){const d=dt(r);if(d)m.set(d,(m.get(d)||0)+N(r[field]))}return Array.from(m,([date,value])=>({date,value})).sort((a,b)=>a.date.localeCompare(b.date))}

function trendFirst(rows,fields){const m=new Map();for(const r of rows){const d=dt(r);if(d)m.set(d,(m.get(d)||0)+firstNum(r,fields))}return Array.from(m,([date,value])=>({date,value})).sort((a,b)=>a.date.localeCompare(b.date))}

function chart(rows){const top=Math.max(...rows.map(r=>Math.abs(N(r.value))),1);return`<div class="chart">${rows.slice(-60).map(r=>`<div class="vbar" data-tip="${dataTip(r.date+' · '+M2(r.value))}" style="height:${Math.max(2,Math.abs(N(r.value))/top*100)}%"></div>`).join('')}</div>`}

function homeRankList(items,opt={}){if(!items.length)return'<div class="empty">当前筛选没有排行数据。</div>';const max=Math.max(1,...items.map(x=>Math.abs(N(x.value))));return`<div class="rank-list ${H(opt.className||'')}">${items.slice(0,opt.limit||18).map((it,i)=>{const pct=Math.max(4,Math.round(Math.abs(N(it.value))/max*100));const color=opt.color?opt.color(it):it.color||'var(--accent)';const owner=opt.showOwner&&it.ownerName?`<span class="rank-owner" style="--owner-color:${H(it.ownerColor||it.color||'#7357ff')}">${H(it.ownerName)}</span>`:'';const attr=opt.attr?opt.attr(it):'';const meta=it.metaHtml||H(it.meta||it.sub||'');return`<button class="rank-item" ${attr} style="--bar-color:${H(color)};--rank-pct:${pct}%" title="${H(it.label||it.key||'-')}"><span class="rank-no">${i+1}</span><span class="rank-main"><span class="rank-title-line"><span class="rank-name">${H(it.label||it.key||'-')}</span>${owner}</span><span class="rank-meta">${meta}</span></span><span class="rank-value">${H(it.valueText||M(it.value))}<small>${H(it.subValue||'')}</small></span></button>`}).join('')}</div>`}
function rank(items,kind=''){if(!items.length)return'<div class="empty">当前筛选没有排行数据。</div>';return`<div class="rank">${items.slice(0,18).map((it,i)=>{const o=kind==='store'?ownByStore.get(it.key):null;return`<div class="rank-row"><span class="muted">${i+1}</span><div><b>${H(it.label||it.key)}</b><small>${H(it.sub||it.meta||'')}</small></div><div class="num"><b>${M(it.value)}</b><br>${o?`<span class="owner"><i class="dot" style="background:${H(o.color||'#7357ff')}"></i>${H(o.name)}</span>`:`<span class="tiny">${H(it.note||it.valueText||'')}</span>`}</div></div>`}).join('')}</div>`}

function avgUnitPrice(r){const q=N(r.quantity);return q?M2(N(r.sales_sar)/q):'—'}
function averageNetUnitPriceText(r){return '均价 '+avgUnitPrice(r)+' SAR'}
function rankMeta(parts){return A(parts).map(p=>`<span class="meta-part">${H(p[0])}<b>${H(p[1])}</b>${p[2]?`<em>${H(p[2])}</em>`:''}</span>`).join('<i class="meta-sep">·</i>')}
function hasNetDeal(r){return netSales(r)>0||netOrders(r)>0||netQty(r)>0}
function dealDays(rs){return uniq(A(rs).filter(hasNetDeal).map(dt).filter(Boolean)).length}
function dealStores(rs){return uniq(A(rs).filter(hasNetDeal).map(sk).filter(Boolean)).length}
function hasPositiveRank(x){return N(x.sales_sar)>0||N(x.quantity)>0||N(x.orders)>0}
function storeRanks(){return Array.from(grp(sales(),r=>sk(r)),([key,rs])=>{const sales=rs.reduce((a,r)=>a+netSales(r),0),qty=rs.reduce((a,r)=>a+netQty(r),0),orders=rs.reduce((a,r)=>a+netOrders(r),0),days=dealDays(rs);const o=ownByStore.get(key);return{key,label:storeDisplayName(key),value:sales,sales_sar:sales,quantity:qty,orders,days,color:o?.color,ownerName:o?.name||'',ownerColor:o?.color||'',meta:`${averageNetUnitPriceText({sales_sar:sales,quantity:qty})} · 订单 ${M(orders)} · 销量 ${M(qty)} 件 · 净成交 ${M(days)} 天`,metaHtml:rankMeta([['均价',avgUnitPrice({sales_sar:sales,quantity:qty}),'SAR'],['订单',M(orders)],['销量',M(qty),'件'],['净成交',M(days),'天']]),valueText:money(sales),subValue:rmb(sales)}}).filter(hasPositiveRank).sort((a,b)=>b.value-a.value)}
function storeQtyRanks(){return storeRanks().map(x=>({...x,value:x.quantity,valueText:M(x.quantity)+' 件',subValue:money(x.sales_sar),meta:`${averageNetUnitPriceText(x)} · 订单 ${M(x.orders)} · 净成交 ${money(x.sales_sar)} · 净成交 ${M(x.days)} 天`,metaHtml:rankMeta([['均价',avgUnitPrice(x),'SAR'],['订单',M(x.orders)],['净成交',M2(x.sales_sar),'SAR'],['净成交',M(x.days),'天']])})).filter(x=>N(x.value)>0||N(x.sales_sar)>0).sort((a,b)=>b.value-a.value)}
function productRanks(){return Array.from(grp(psales(),r=>pkey(r)),([key,rs])=>{const sales=rs.reduce((a,r)=>a+netSales(r),0),qty=rs.reduce((a,r)=>a+netQty(r),0),orders=rs.reduce((a,r)=>a+netOrders(r),0),stores=dealStores(rs),days=dealDays(rs);return{key,label:prod(rs[0]),value:sales,sales_sar:sales,quantity:qty,orders,stores,days,meta:`${averageNetUnitPriceText({sales_sar:sales,quantity:qty})} · 销量 ${M(qty)} 件 · 订单 ${M(orders)} · 覆盖 ${M(stores)} 店 · 净成交 ${M(days)} 天`,metaHtml:rankMeta([['均价',avgUnitPrice({sales_sar:sales,quantity:qty}),'SAR'],['销量',M(qty),'件'],['订单',M(orders)],['覆盖',M(stores),'店'],['净成交',M(days),'天']]),valueText:money(sales),subValue:rmb(sales)}}).filter(hasPositiveRank).sort((a,b)=>b.value-a.value)}
function productQtyRanks(){return productRanks().map(x=>({...x,value:x.quantity,valueText:M(x.quantity)+' 件',subValue:money(x.sales_sar),meta:`${averageNetUnitPriceText(x)} · 净成交 ${money(x.sales_sar)} · 订单 ${M(x.orders)} · 覆盖 ${M(x.stores)} 店 · 净成交 ${M(x.days)} 天`,metaHtml:rankMeta([['均价',avgUnitPrice(x),'SAR'],['净成交',M2(x.sales_sar),'SAR'],['订单',M(x.orders)],['覆盖',M(x.stores),'店'],['净成交',M(x.days),'天']])})).filter(x=>N(x.value)>0||N(x.sales_sar)>0).sort((a,b)=>b.value-a.value)}

function metricMatrix(heads,rows,cols,extra=''){return`<div class="metric-matrix cols-${cols}${extra?` ${H(extra)}`:''}">${heads.map(h=>`<div class="matrix-cell head">${H(h)}</div>`).join('')}${rows.map(r=>`<div class="matrix-cell label">${H(r.label)}</div>${r.cells.map(c=>`<div class="matrix-cell value">${c}</div>`).join('')}`).join('')}</div>`}
function metricCard(title,sub,heads,rows,tip,extra=''){const help=tip?` <em class="help" data-tip="${dataTip(tip)}" aria-label="${H(tip)}" tabindex="0">?</em>`:'';return`<article class="overview-matrix-card"><div class="matrix-card-head"><h4>${H(title)}${help}</h4><div class="sub">${H(sub)}</div></div>${metricMatrix(heads,rows,Math.max(1,heads.length-1),extra)}</article>`}
function homeKpis(){const s=salesSummary(),req=retRequestSummary(),ordRet=retOrderSummary(),p=profSum(),tr=trafficSummary(),iv=inventorySummary();const rankingsLoading=sourceLoading('homeRankings',s.rows);const afterLoading=sourceLoading('afterSales',req.rows);const profitLoading=sourceLoading(String(S.q||'').trim()?'profit':'homeProfit',p.rows);const trafficLoading=sourceLoading('productTrafficDaily',tr.rows);const invLoading=sourceLoading('financeData',iv.rows);const active=v=>v==null?'—':M(v)+' 个';const profitLoss=p.loss,profitRtv=p.rtv,profitStorage=p.storage;return`<section class="kpi-six">`+
metricCard('当前时段成交额',selectedRangeText()+' · '+homeScopeSubtitle(),['口径','SAR','RMB'],[
{label:'总成交额',cells:[htmlValue(moneyCell(s.gross),rankingsLoading),htmlValue(rmbCell(s.gross),rankingsLoading)]},
{label:'净成交额',cells:[htmlValue(moneyCell(s.net),rankingsLoading),htmlValue(rmbCell(s.net),rankingsLoading)]}], '总成交额是原始成交规模；净成交额扣除退货、仅退款、派送失败等反转订单。')+
metricCard('当前时段订单 / 销量 / 动销',selectedRangeText()+' · '+homeScopeSubtitle(),['口径','订单','销量','动销货号'],[
{label:'总订单/销量',cells:[htmlValue(M(s.gord)+' 单',rankingsLoading),htmlValue(M(s.gqty)+' 件',rankingsLoading),htmlValue(active(s.gactive),rankingsLoading)]},
{label:'净订单/销量',cells:[htmlValue(M(s.ord)+' 单',rankingsLoading),htmlValue(M(s.qty)+' 件',rankingsLoading),htmlValue(active(s.active),rankingsLoading)]}], '总订单/销量看原始出单；净订单/销量看最终仍保留成交额的订单。')+
metricCard('当前时段退货 / 售后',selectedRangeText()+' · 双口径',['口径','数量','SAR','RMB'],[
{label:'售后申请时间',cells:[htmlValue(M(req.cases)+' 单',afterLoading),htmlValue(moneyCell(req.amount),afterLoading),htmlValue(rmbCell(req.amount),afterLoading)]},
{label:'订单创建时间',cells:[htmlValue(M(ordRet.cases)+' 单',rankingsLoading),htmlValue(moneyCell(ordRet.amount),rankingsLoading),htmlValue(rmbCell(ordRet.amount),rankingsLoading)]}], '申请时间用于发现当天售后异常；订单创建时间用于和订单成熟窗口复盘。')+
metricCard('当前时段真实利润',selectedRangeText()+' · 双测算',['口径','SAR','RMB','比率'],[
{label:'退货全损保守',cells:[htmlValue(moneyCell(profitLoss),profitLoading),htmlValue(rmbCell(profitLoss),profitLoading),htmlValue(PCT(p.revenue?profitLoss/p.revenue:null),profitLoading)]},
{label:'RTV入仓测算',cells:[htmlValue(moneyCell(profitRtv),profitLoading),htmlValue(rmbCell(profitRtv),profitLoading),htmlValue(PCT(p.revenue?profitRtv/p.revenue:null),profitLoading)]},
{label:'已扣仓储费',cells:[htmlValue(moneyCell(profitStorage),profitLoading),htmlValue(rmbCell(profitStorage),profitLoading),htmlValue(PCT(p.revenue?profitStorage/p.revenue:null),profitLoading)]}], '真实利润为扣仓储费后利润；仓储费来自 ET 物流仓服账单/明细，店铺与分组按净销售额分摊，货号层优先使用 ET 仓储费导出明细。','profit-matrix')+
metricCard('当前时段流量',selectedRangeText()+' · 日×店×货号',['指标','数值','说明'],[
{label:'曝光 / 访客',cells:[htmlValue(M(tr.exp)+' / '+M(tr.uv),trafficLoading),smallValue('点击率 '+PCT(tr.click),trafficLoading)]},
{label:'成交 / 支付率',cells:[htmlValue(M(tr.sale)+' 件 / '+PCT(tr.pay),trafficLoading),smallValue(tr.rangeNote,trafficLoading)]}], '流量按当前日期、店铺/负责人、货号搜索聚合；点击率/支付率按分子分母重算。历史范围不再静默回退到最新可用日。','traffic-matrix')+
metricCard('当前库存 / 去化','当前快照 · '+M(iv.count)+' 货号 · 全局库存',['指标','数值','说明'],[
{label:'供给 / 可售',cells:[htmlValue(M(iv.totalSupply)+' / '+M(iv.available)+' 件',invLoading),smallValue('在库 '+M(iv.onhand)+' · 在途 '+M(iv.incoming),invLoading)]},
{label:'去化周期',cells:[htmlValue(iv.days==null?'—':M2(iv.days)+' 天',invLoading),smallValue(iv.daily>0?'日销 '+M2(iv.daily)+' 件':'无动销速度',invLoading)]}], '去化周期按总供给/加权日销汇总，不平均各货号天数；ET可售和成本表供给是不同库存口径。','inventory-matrix')+'</section>'}

const TREND_METRICS={sales:{label:'成交额',money:true},quantity:{label:'销量'},returns:{label:'售后'},profit:{label:'利润',money:true},traffic:{label:'流量'},inventory:{label:'库存'}};
function trendMetricButtons(){return`<div class="trend-toggle">${Object.entries(TREND_METRICS).map(([k,m])=>`<button type="button" class="${S.trendMetric===k?'active':''}" data-trend-metric="${H(k)}">${H(m.label)}</button>`).join('')}</div>`}
function bucketLabel(id,kind){return kind==='month'?id:id}
function bucket(map,id,kind){const row=map.get(id)||{id,label:bucketLabel(id,kind)};map.set(id,row);return row}
function rowsFromMap(map){return Array.from(map.values()).sort((a,b)=>String(a.id).localeCompare(String(b.id)))}
function addTrend(map,kind,date,vals){if(!date)return;const id=kind==='month'?monthId(date):date;const r=bucket(map,id,kind);Object.entries(vals).forEach(([k,v])=>r[k]=N(r[k])+N(v))}
function buildTrendSeries(kind,metric=S.trendMetric){const map=new Map();if(metric==='sales'||metric==='quantity'){for(const r of sales()){const d=dt(r);addTrend(map,kind,d,metric==='sales'?{net:netSales(r),gross:grossSales(r)}:{net:netQty(r),gross:grossQty(r)})}return{series:rowsFromMap(map),lines:[{key:'net',label:metric==='sales'?'净成交额':'净销量',color:metric==='sales'?'#10b981':'#60a5fa'},{key:'gross',label:metric==='sales'?'总成交额':'总销量',color:metric==='sales'?'#f59e0b':'#a78bfa'}],note:'按当前店铺/负责人、货号和日期筛选重算。'}}
if(metric==='returns'){for(const r of sales()){const d=dt(r);addTrend(map,kind,d,{order:Math.max(0,grossOrders(r)-netOrders(r))})}for(const r of returns()){const d=ISO(r.request_time||dt(r));addTrend(map,kind,d,{request:1})}return{series:rowsFromMap(map),lines:[{key:'request',label:'售后申请时间',color:'#ef4444'},{key:'order',label:'订单创建时间',color:'#f97316'}],note:'申请时间来自售后明细；订单创建时间来自总订单与净订单差额。'}}
if(metric==='profit'){for(const r of hprofit()){const d=dt(r);addTrend(map,kind,d,{loss:profitAmountLoss(r),rtv:profitAmountRtv(r)})}return{series:rowsFromMap(map),lines:[{key:'loss',label:'退货全损保守',color:'#14b8a6'},{key:'rtv',label:'RTV入仓测算',color:'#f97316'}],note:'含仓储真实利润；两条线与顶部利润卡同口径。'}}
if(metric==='traffic'){const tr=trafficSummary(false);for(const r of tr.rows){const d=dt(r);addTrend(map,kind,d,{eps:firstNum(r,['eps_uv','exposure_uv','exposure_cnt','impressions']),uv:firstNum(r,['goods_uv','uv','visitor_cnt','visitors']),sale:firstNum(r,['sale_cnt','pay_order_cnt','quantity'])})}return{series:rowsFromMap(map),lines:[{key:'eps',label:'曝光量',color:'#06b6d4'},{key:'uv',label:'访客量',color:'#3b82f6'},{key:'sale',label:'成交件数',color:'#8b5cf6'}],rangeText:tr.rangeText,note:(tr.effectiveShifted?`已按流量最新可用区间 ${tr.rangeText} 展示。`:'')+'绝对量同轴展示；点击率/支付率留在顶部流量卡。'}}
if(metric==='inventory'){const latestByMonth=new Map();for(const r of invTrendLoose()){const d=dt(r);if(!d)continue;const id=kind==='month'?monthId(d):d;const row=latestByMonth.get(id)||{id,label:id,date:''};if(!row.date||d>=row.date){row.date=d;row.usable=firstNum(r,['usable_inventory','platform_display_stock','available_qty']);row.total=firstNum(r,['inventory_quantity','total_inventory','platform_total_stock']);row.locked=firstNum(r,['order_locked_quantity','pay_locked_quantity','locked_inventory'])}latestByMonth.set(id,row)}return{series:rowsFromMap(latestByMonth),lines:[{key:'usable',label:'可售展示库存',color:'#14b8a6'},{key:'total',label:'总展示库存',color:'#60a5fa'},{key:'locked',label:'锁定库存',color:'#f59e0b'}],note:(kind==='month'?'月图取每月最新快照，不累加库存。':'来自前台展示库存每日快照。')}}
return{series:[],lines:[],note:''}}
function trendValueText(v,metric=S.trendMetric){const meta=TREND_METRICS[metric]||{};return meta.money?money(v):M(v)}
function niceCeil(v){const n=Math.abs(N(v));if(n<=10)return 10;const p=Math.pow(10,Math.floor(Math.log10(n)));return Math.ceil(n/p)*p}
function dataTip(v){return H(v).replace(/\n/g,'&#10;')}
function lineChart(kind,metric=S.trendMetric){
const built=buildTrendSeries(kind,metric),series=built.series||[],lines=built.lines||[];
const meta=TREND_METRICS[metric]||{};
if(!series.length||!lines.length)return`<div class="empty">当前时间段 ${H(selectedRangeText())} 暂无${H(meta.label||metric)}趋势数据。</div>`;
const keys=lines.map(x=>x.key),colors=Object.fromEntries(lines.map(x=>[x.key,x.color])),labels=Object.fromEntries(lines.map(x=>[x.key,x.label]));
const overlay=(metric==='sales'||metric==='quantity')&&keys.includes('net')&&keys.includes('gross');
const canOverlay=r=>{const net=N(r.net),gross=N(r.gross);return gross>=0&&net>=0&&net<=gross};
const vals=series.flatMap(r=>keys.map(k=>N(r[k])));
const maxRaw=Math.max(1,...vals),minRaw=Math.min(0,...vals);
const max=niceCeil(maxRaw),min=minRaw<0?-niceCeil(Math.abs(minRaw)):0,span=Math.max(1,max-min);
const w=1280,h=306,padL=72,padR=28,padT=28,padB=54,plotW=w-padL-padR,plotH=h-padT-padB;
const yFor=v=>padT+(1-((N(v)-min)/span))*plotH,zeroY=yFor(0);
const ticks=[min,min+span*.25,min+span*.5,min+span*.75,max];
const grid=ticks.map(v=>`<line class="grid-line" x1="${padL}" y1="${yFor(v).toFixed(1)}" x2="${w-padR}" y2="${yFor(v).toFixed(1)}"></line><text class="axis" text-anchor="end" x="${padL-8}" y="${(yFor(v)+4).toFixed(1)}">${H(compact(v))}</text>`).join('');
const groupW=plotW/Math.max(1,series.length),dense=groupW<keys.length*7,innerGap=dense?0:4,groupInner=Math.max(1,groupW*(dense?0.88:0.72));
const groupedBarW=Math.max(dense?0.9:2,Math.min(28,(groupInner-innerGap*(keys.length-1))/Math.max(1,keys.length)));
const overlayTotalW=Math.max(dense?1.2:3,Math.min(34,groupW*(dense?0.74:0.52)));
const overlayNetW=Math.max(dense?0.85:2,overlayTotalW*.56);
const groupX=i=>padL+i*groupW+groupW/2;
const groupedBarX=(i,ki)=>groupX(i)-(groupedBarW*keys.length+innerGap*(keys.length-1))/2+ki*(groupedBarW+innerGap);
const gid=k=>`trend-${kind}-${metric}-${k}`.replace(/[^a-z0-9_-]/gi,'-');
const defs=`<defs>${lines.map(l=>`<linearGradient id="${H(gid(l.key))}" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stop-color="${H(l.color)}" stop-opacity=".96"></stop><stop offset="1" stop-color="${H(l.color)}" stop-opacity=".48"></stop></linearGradient>`).join('')}</defs>`;
const rectFor=(klass,x,width,v,fill,tip)=>{const y=yFor(v),top=Math.min(y,zeroY),height=Math.abs(zeroY-y),rx=Math.min(6,Math.max(1,width/2));return`<rect class="trend-bar ${klass}" data-tip="${tip}" x="${x.toFixed(1)}" y="${top.toFixed(1)}" width="${width.toFixed(1)}" height="${height.toFixed(1)}" rx="${rx.toFixed(1)}" fill="${fill}"></rect>`};
const overlayDetail=r=>{const gross=N(r.gross),net=N(r.net),diff=gross-net;return`${labels.gross}：${trendValueText(gross,metric)}\n${labels.net}：${trendValueText(net,metric)}\n反转/扣减：${trendValueText(diff,metric)}${canOverlay(r)?'':'\n口径关系异常，已并列显示'}`};
const bars=overlay?series.map((r,i)=>{const tip=dataTip(r.label+'\n'+overlayDetail(r));if(canOverlay(r)){const cx=groupX(i),gross=N(r.gross),net=N(r.net);return rectFor('trend-bar-total',cx-overlayTotalW/2,overlayTotalW,gross,`url(#${H(gid('gross'))})`,tip)+rectFor('trend-bar-net',cx-overlayNetW/2,overlayNetW,net,`url(#${H(gid('net'))})`,tip)}return keys.map((k,ki)=>rectFor('trend-bar-fallback',groupedBarX(i,ki),groupedBarW,N(r[k]),`url(#${H(gid(k))})`,tip)).join('')}).join(''):keys.map((k,ki)=>series.map((r,i)=>{const tip=dataTip(labels[k]+' · '+r.label+'\n'+trendValueText(r[k],metric));return rectFor('',groupedBarX(i,ki),groupedBarW,N(r[k]),`url(#${H(gid(k))})`,tip)}).join('')).join('');
const every=series.length<=7?1:Math.ceil(series.length/(kind==='month'?7:6));
const valueLabels=overlay?series.map((r,i)=>{if(!(i===0||i===series.length-1||i%every===0))return'';const v=N(r.net);if(!v&&i!==0&&i!==series.length-1)return'';const x=groupX(i),y=yFor(v),anchor=i===0?'start':i===series.length-1?'end':'middle';return`<text class="value-label bar-value-label" text-anchor="${anchor}" x="${x.toFixed(1)}" y="${Math.max(14,y-7).toFixed(1)}" fill="${colors.net}">${H(compact(v))}</text>`}).join(''):keys.map((k,ki)=>series.map((r,i)=>{if(!(i===0||i===series.length-1||i%every===0))return'';const v=N(r[k]);if(!v&&i!==0&&i!==series.length-1)return'';const x=groupedBarX(i,ki)+groupedBarW/2,y=yFor(v),positive=v>=0,ty=positive?Math.max(14,y-7-ki*12):Math.min(h-padB+20,y+14+ki*12);const anchor=i===0?'start':i===series.length-1?'end':'middle';return`<text class="value-label bar-value-label" text-anchor="${anchor}" x="${x.toFixed(1)}" y="${ty.toFixed(1)}" fill="${colors[k]}">${H(compact(v))}</text>`}).join('')).join('');
const hitW=Math.max(10,Math.min(120,groupW*.92));
const hits=series.map((r,i)=>{const x=Math.max(padL,Math.min(w-padR-hitW,groupX(i)-hitW/2));const detail=overlay?overlayDetail(r):keys.map(k=>labels[k]+'：'+trendValueText(r[k],metric)).join('\n');const tip=dataTip(r.label+'\n'+detail);return`<rect class="chart-hit" data-tip="${tip}" x="${x.toFixed(1)}" y="${padT}" width="${hitW.toFixed(1)}" height="${plotH}"></rect>`}).join('');
const axisEvery=Math.ceil(series.length/6);
const axis=series.map((r,i)=>(series.length<=8||i===0||i===series.length-1||i%axisEvery===0)?`<text class="axis" text-anchor="${i===0?'start':i===series.length-1?'end':'middle'}" x="${groupX(i).toFixed(1)}" y="${h-10}">${H(r.label)}</text>`:'').join('');
const latest=series.at(-1)||{};
const legend=overlay?`<span class="legend-net"><i style="--c:${colors.net}"></i>${H(labels.net)}：${H(trendValueText(latest.net||0,metric))}</span><span class="legend-total"><i style="--c:${colors.gross}"></i>${H(labels.gross)}：${H(trendValueText(latest.gross||0,metric))}</span><span class="legend-diff"><i style="--c:#9b8b77"></i>反转/扣减：${H(trendValueText(N(latest.gross)-N(latest.net),metric))}</span>`:keys.map(k=>`<span><i style="--c:${colors[k]}"></i>${H(labels[k])}：${H(trendValueText(latest[k]||0,metric))}</span>`).join('');
return`<div class="line-chart bar-chart${overlay?' overlay-bar-chart':''}"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="${H((kind==='month'?'月':'日')+(meta.label||metric)+'柱状趋势')}">${defs}<rect class="plot-band" x="${padL}" y="${padT}" width="${plotW}" height="${plotH}" rx="14"></rect>${grid}<line class="axis-line" x1="${padL}" y1="${padT}" x2="${padL}" y2="${h-padB}"></line><line class="axis-line" x1="${padL}" y1="${h-padB}" x2="${w-padR}" y2="${h-padB}"></line><line class="zero-line" x1="${padL}" y1="${zeroY.toFixed(1)}" x2="${w-padR}" y2="${zeroY.toFixed(1)}"></line>${bars}${valueLabels}${axis}${hits}</svg><div class="chart-legend">${legend}</div><p class="sub">时间段：${H(built.rangeText||`${S.start} 至 ${S.end}`)}；当前显示 ${M(series.length)} 个${kind==='month'?'月份':'日期'}。${H(built.note||'')}</p></div>`}
function trendPanel(kind){const metric=S.trendMetric;const needed=metric==='profit'?(String(S.q||'').trim()?'profit':'homeProfit'):metric==='traffic'?'productTrafficDaily':metric==='inventory'?'inventoryTrend':'homeRankings';const built=buildTrendSeries(kind,metric);if(sourceLoading(needed,built.series))return`<section class="panel trend-panel"><h4>${kind==='month'?'月趋势':'日趋势'} · ${H(TREND_METRICS[metric]?.label||metric)}</h4><p class="sub">${H(SL[needed]||needed)} 加载中</p><div class="empty">正在加载${H(SL[needed]||needed)}，加载完成后自动刷新本图。</div></section>`;return`<section class="panel trend-panel"><h4>${kind==='month'?'月趋势':'日趋势'} · ${H(TREND_METRICS[metric]?.label||metric)}</h4><p class="sub">${H(metric==='inventory'?inventoryScopeNote():homeScopeSubtitle())}</p>${lineChart(kind,metric)}</section>`}

function auditHtml(){const a=D.audit;if(!a)return'<span class="audit-warn">未找到体检文件</span>';if(a.ok&&!a.warnings&&!a.errors)return'<span class="audit-ok">通过</span>';if(a.errors)return`<span class="audit-bad">${H(a.errors)} 个错误</span>`;return`<span class="audit-warn">${H(a.warnings||0)} 个提醒</span>`}
function healthItems(){const dates=D.dates||{};const costTs=dates.manualCostFileUpdatedAt||dates.manualCostUpdatedAt||dates.etStorageDetailUpdatedAt||dates.etStorageUpdatedAt||dates.manualStorageUpdatedAt||'';return[['BI 页面生成',fmtStamp(genAt())],['SHEIN 销售源',fmtStamp(dates.salesUpdatedAt||dates.salesDate)],['SHEIN 业务域',fmtStamp(dates.businessUpdatedAt||dates.businessDate)],['SHEIN 链接表现',fmtStamp(dates.linkUpdatedAt||dates.linkDate)],['成本表文件',fmtStamp(costTs)],['ET 货代仓',fmtStamp(dates.etUpdatedAt)],['数据体检',auditHtml()]]}
function sideStatusHtml(){return`<div class="side-status-head">数据状态</div>${healthItems().map(([k,v])=>`<div class="side-status-row"><span>${H(k)}</span><strong title="${H(String(v).replace(/<[^>]+>/g,''))}">${String(v).includes('<span')?v:H(v)}</strong></div>`).join('')}`}
function healthStrip(){return`<section class="status-strip">${healthItems().map(([k,v])=>`<div><strong>${H(k)}</strong><span>${String(v).includes('<span')?v:H(v)}</span></div>`).join('')}</section>`}

function home(){ensure('home',true);const storeBySales=storeRanks(),storeByQty=storeQtyRanks(),productBySales=productRanks(),productByQty=productQtyRanks();return`${homeKpis()}${head('趋势','按钮只切换当前趋势指标；页面只保留一个日图和一个月图，图上直接显示关键数字。',trendMetricButtons())}<div class="trend-stack">${trendPanel('day')}${trendPanel('month')}</div>${head('排行榜','保留 V1 的店铺/产品净成交额与净销量四块信息，并恢复条形比例图。',chips(homeNeeds()))}<section class="rank-grid"><div class="panel rank-panel"><h4>店铺净成交额排行</h4><p class="sub">当前范围 ${M(storeBySales.length)} 店 · ${H(selectedRangeText())} · 天数=净成交日</p>${homeRankList(storeBySales,{limit:storeBySales.length,showOwner:true,color:it=>it.color||'#10b981',attr:it=>`data-home-store="${H(it.key)}"`})}</div><div class="panel rank-panel"><h4>店铺净销量排行</h4><p class="sub">当前范围 ${M(storeByQty.length)} 店 · 按净成交销量件数排序；天数只算净成交日。</p>${homeRankList(storeByQty,{limit:storeByQty.length,showOwner:true,color:it=>it.color||'#60a5fa',attr:it=>`data-home-store="${H(it.key)}"`})}</div><div class="panel rank-panel"><h4>产品净成交额排行</h4><p class="sub">标准货号归并，展示均价、销量、订单、覆盖店和净成交天数。</p>${homeRankList(productBySales,{className:'product-rank',color:()=> '#db2777',attr:it=>`data-home-product="${H(it.key)}"`})}</div><div class="panel rank-panel"><h4>产品净销量排行</h4><p class="sub">按净成交销量件数排序；天数只算净成交日。</p>${homeRankList(productByQty,{className:'product-rank',color:()=> '#a855f7',attr:it=>`data-home-product="${H(it.key)}"`})}</div></section>`}

const ORDER_STATUS_FILTERS=[
  ['all','全部'],['pending','待处理/待发货'],['shipped','已发货/运输中'],['platform_unclosed','平台未闭环'],['pending_recheck','待复查'],['done','已签收'],['mixed','混合状态'],['cancelled','取消/关闭'],['returning','未妥投退回'],['cod','COD'],['abnormal','异常'],['other','其他/未识别']
];
function orderId(r){return [sk(r),r?.order_no||r?.bill_no||r?.place_order_package_id||`${pkey(r)}-${r?.order_create_time||dt(r)}`].join('|')}
function uniqueOrderCount(rows){return new Set(A(rows).map(orderId)).size}
function isCodOrder(r){if(r?.is_cod===true||r?.is_cod===1||String(r?.is_cod).toLowerCase()==='true')return true;const txt=[r?.payment_label,r?.payment_method,r?.tags].map(x=>String(x||'').toUpperCase()).join(' ');if(/NON[_ -]?COD/.test(txt))return false;return /(^|[^A-Z0-9])COD($|[^A-Z0-9])/.test(txt)}
function orderStatusText(r){return String(r?.order_status_desc||r?.perform_status_desc||r?.goods_performance_status_desc||r?.order_status||'').trim()}
function staleShipAge(r){const d=ISO(r?.created_date||r?.order_create_time);if(!d)return false;const t=new Date(`${d}T00:00:00+08:00`).getTime();return Number.isFinite(t)&&Date.now()-t>10*86400_000}
function orderStatusKey(r){const g=String(r?.order_status_group||'').trim();if(g&&g!=='cod')return g;const s=orderStatusText(r),w=String(r?.waybill_status||r?.tag_desc||'');if(/未妥投|退回|拒收/.test(s+w))return'returning';if(/异常|失败|超时|风控|拦截/.test(s+w))return'abnormal';if(/取消|关闭/.test(s))return'cancelled';if(/已签收|已完成|妥投/.test(s))return'done';if(/尾程已发货|已发货|运输|揽收|包裹已揽收/.test(s+w))return staleShipAge(r)?'pending_recheck':'shipped';if(/待处理|待发货|待揽收|待出库|待|下单成功|已打印面单/.test(s+w))return staleShipAge(r)?'pending_recheck':'pending';return'other'}
function orderStatusMatch(r,key){if(key==='all')return true;if(key==='cod')return isCodOrder(r);if(key==='abnormal')return orderStatusKey(r)==='abnormal'||/失败|异常|超时/.test(orderStatusText(r)+String(r?.waybill_status||r?.tag_desc||''));return orderStatusKey(r)===key}
function orderStatusBadge(r){const k=orderStatusKey(r),raw=orderStatusText(r)||'未知';const label=k==='platform_unclosed'?'平台未闭环':k==='pending_recheck'?'待复查':k==='mixed'?'混合状态':raw;return`<span class="order-status ${H(k)}" title="${H(raw)}">${H(label)}</span>`}
function paymentBadge(r){return isCodOrder(r)?'<span class="cod-badge">COD</span>':''}
function normalizedOrderText(x){return String(x||'').replace(/[\s_\-·：:]/g,'').toUpperCase()}
function paymentDetailText(r){const raw=String(r?.payment_label||r?.payment_method||'').trim();const n=normalizedOrderText(raw);if(!raw||n==='COD'||n==='NONCOD')return'';return raw}
function orderPaymentHtml(r){const parts=[paymentBadge(r),paymentDetailText(r)?H(paymentDetailText(r)):'' ].filter(Boolean);return parts.join(' ')}
function orderStatusMetaText(r){if(r?.order_status_source==='recheck'){const n=N(r?.status_check_count)||1;return `复查 ${M(n)} 次 · ${fmtStamp(r?.status_checked_at||r?.updated_at)}`;}return `销售源 · ${fmtStamp(r?.updated_at)}`}

function orderItems(r){return A(r?.items)}
function orderProductMainText(r){if(N(r?.item_count)>1||N(r?.product_count)>1)return String(r?.product_summary||'多商品订单');return prod(r)}
function orderProductSubText(r){const its=orderItems(r);if(its.length>1){const details=String(r?.product_detail_summary||'').trim()||its.slice(0,5).map(it=>[it?.standard_goods_sn,it?.skc,it?.goods_title].filter(Boolean).join(' · ')).filter(Boolean).join('；');const extra=its.length>5?`；+${M(its.length-5)}项`:'';return details+extra}const main=String(prod(r)||'').trim();const nm=normalizedOrderText(main);const vals=[pkey(r),r?.skc,r?.sku,r?.goods_title].map(x=>String(x||'').trim()).filter(Boolean);for(const v of vals){if(normalizedOrderText(v)&&normalizedOrderText(v)!==nm)return v}return''}
function primaryExpressText(r){return String(r?.express_code||r?.express_no||'').trim()}
function secondaryExpressText(r){const a=String(r?.express_code||'').trim(),b=String(r?.express_no||'').trim();return a&&b&&a!==b?b:''}
function etShipperText(r){const code=String(r?.et_shipper_code||'').trim().toUpperCase();const name=String(r?.et_shipper_name||'').trim();if(name)return name;if(code)return code;return'无'}
function etOutboundMeta(r){const parts=[];if(r?.et_outbound_status)parts.push(String(r.et_outbound_status));if(r?.et_outbound_time)parts.push(shortDate(r.et_outbound_time));else if(r?.et_outbound_create_time)parts.push(shortDate(r.et_outbound_create_time));if(r?.et_logistics_title)parts.push(String(r.et_logistics_title));return parts.join(' · ')}
function etOutboundHtml(r){const id=String(r?.et_outbound_id||'').trim();if(!id)return'<small>ET 未关联</small>';const meta=etOutboundMeta(r);const url=String(r?.et_detail_url||'').trim();const idHtml=url?`<a class="mono et-link" href="${H(url)}" target="_blank" rel="noreferrer">${H(id)}</a>`:`<span class="mono">${H(id)}</span>`;return`<small><span class="et-label">ET</span> ${idHtml}${meta?` · ${H(meta)}`:''}</small>`}
function packageText(r){return secondaryExpressText(r)||String(r?.place_order_package_id||'').trim()}
function statusDistributionText(r){const d=r?.status_distribution;if(!d||typeof d!=='object')return'';const names={abnormal:'异常',returning:'未妥投退回',platform_unclosed:'平台未闭环',pending_recheck:'待复查',pending:'待处理',shipped:'运输中',done:'已签收',cancelled:'取消',mixed:'混合',other:'其他'};return Object.entries(d).map(([k,v])=>`${names[k]||k} ${M(v)}`).join(' / ')}
function orderTimelineTip(r){const lines=[];if(N(r?.item_count)>1)lines.push(`商品：${String(r?.product_summary||'多商品订单')}（${String(r?.product_detail_summary||'').slice(0,180)}）`);const sd=statusDistributionText(r);if(sd)lines.push(`商品状态：${sd}`);lines.push(`订单创建：${fmtStamp(r?.order_create_time||r?.created_date)}`);if(r?.updated_at)lines.push(`状态更新：${fmtStamp(r.updated_at)}`);if(r?.status_checked_at)lines.push(`订单复查：第 ${M(N(r?.status_check_count)||1)} 次 · ${fmtStamp(r.status_checked_at)}`);if(r?.print_time)lines.push(`打单：${fmtStamp(r.print_time)}`);if(r?.collect_time)lines.push(`揽收：${fmtStamp(r.collect_time)}`);const ws=[r?.waybill_status,r?.tag_desc].filter(Boolean).join(' · ');if(ws)lines.push(`包裹状态：${ws}`);const etMeta=etOutboundMeta(r);if(etMeta)lines.push(`ET状态：${etMeta}`);if(r?.et_shipper_code||r?.et_shipper_name)lines.push(`发货人：${etShipperText(r)}`);if(N(r?.waybill_count)>1)lines.push(`包裹数：${M(r.waybill_count)}（当前展示最新一条物流）`);if(orderStatusKey(r)==='platform_unclosed')lines.push('提示：该单已重新向 SHEIN 查询，但平台当前仍返回非终态；不按真实运输中统计，并会继续复查。');if(orderStatusKey(r)==='pending_recheck')lines.push('提示：该单超过10天仍非终态，正在等待后台复查任务刷新。');if(/已签收/.test(orderStatusText(r))&&!r?.signed_time)lines.push('签收：当前订单状态为已签收（暂无精确签收时间）');if(!(r?.express_no||r?.express_code))lines.push('物流：暂无云端精确物流单号');if(!r?.et_outbound_id)lines.push('ET出库：未关联到 ET 出库单');return lines.join('\n')}
function orderStatusTabs(rows){const counts=new Map(ORDER_STATUS_FILTERS.map(([k])=>[k,uniqueOrderCount(k==='all'?rows:rows.filter(r=>orderStatusMatch(r,k)))]));return`<div class="status-tabs">${ORDER_STATUS_FILTERS.map(([k,label])=>`<button class="status-filter ${S.orderStatus===k?'active':''}" data-order-status="${H(k)}"><span>${H(label)}</span><b>${M(counts.get(k)||0)}</b></button>`).join('')}</div>`}
function orderPager(page,total,totalRows,pageSize){const prev=Math.max(1,page-1),next=Math.min(total,page+1);const sizes=[50,80,150,300];return`<div class="pager"><button class="btn" data-order-page="1" ${page<=1?'disabled':''}>首页</button><button class="btn" data-order-page="${prev}" ${page<=1?'disabled':''}>上一页</button><span>第 <input class="page-input" data-order-page-input type="number" min="1" max="${H(total)}" value="${H(page)}"> / <b>${M(total)}</b> 页</span><button class="btn" data-order-page="${next}" ${page>=total?'disabled':''}>下一页</button><button class="btn" data-order-page="${total}" ${page>=total?'disabled':''}>末页</button><label>每页 <select data-order-page-size>${sizes.map(n=>`<option value="${n}" ${Number(pageSize)===n?'selected':''}>${n}</option>`).join('')}</select> 条</label><span>共 ${M(totalRows)} 单</span></div>`}
function orderTable(rows){return`<div class="table-wrap order-table-wrap"><table class="order-table"><colgroup><col class="c-time"><col class="c-store"><col class="c-order"><col class="c-product"><col class="c-num"><col class="c-num"><col class="c-status"><col class="c-shipper"><col class="c-waybill"></colgroup><thead><tr><th>订单时间</th><th>店铺</th><th>订单</th><th>货号 / 商品</th><th class="num">金额</th><th class="num">件数</th><th>状态</th><th>发货人</th><th>物流 / ET出库</th></tr></thead><tbody>${rows.map(r=>{const tip=dataTip(orderTimelineTip(r));const express=primaryExpressText(r)||'—';const pkg=packageText(r);const wayStatus=[r.waybill_status,r.tag_desc].filter(Boolean).join(' · ');const multi=N(r.waybill_count)>1?`<em class="multi-waybill">多包裹 ${M(r.waybill_count)}</em>`:'';const pkgMeta=[pkg?`包裹号 ${pkg}`:'',wayStatus].filter(Boolean).join(' · ');return`<tr><td><b>${H(shortDate(r.order_create_time||r.created_date))}</b><small>${H(fmtStamp(r.order_create_time).replace(/^.*? /,''))}</small></td><td>${H(storeDisplayName(sk(r)))}</td><td><b class="mono">${H(r.order_no||r.bill_no||'—')}</b>${orderPaymentHtml(r)?`<small>${orderPaymentHtml(r)}</small>`:''}</td><td><b>${H(orderProductMainText(r))}</b>${orderProductSubText(r)?`<small class="product-detail" title="${H(orderProductSubText(r))}">${H(orderProductSubText(r))}</small>`:''}</td><td class="num"><b>${M2(r.sales_sar)}</b><small>SAR</small></td><td class="num"><b>${M(r.quantity)}</b><small>件</small></td><td>${orderStatusBadge(r)}<small>${H(orderStatusMetaText(r))}</small></td><td><b class="shipper-code">${H(etShipperText(r))}</b></td><td data-tip="${tip}"><b class="mono">${H(express)}</b>${etOutboundHtml(r)}${pkgMeta?`<small>${multi}${H(pkgMeta)}</small>`:''}</td></tr>`}).join('')}</tbody></table></div>`}
function ordersPage(){ensure('orders',true);if(!A(D.orders).length&&SS.orders?.status!=='ok')return intro('订单中心','按订单创建时间查看成交、取消、履约、COD 和物流状态。')+wait('orders');
const base=orders().slice().sort((a,b)=>String(b.order_create_time||dt(b)).localeCompare(String(a.order_create_time||dt(a))));const active=base.filter(r=>orderStatusMatch(r,S.orderStatus||'all'));const pageSize=Math.max(20,Math.min(500,Number(S.orderPageSize)||80)),totalPages=Math.max(1,Math.ceil(active.length/pageSize));S.orderPage=Math.min(Math.max(1,Number(S.orderPage)||1),totalPages);const start=(S.orderPage-1)*pageSize,rs=active.slice(start,start+pageSize);const maxUpdated=base.map(r=>r.updated_at).filter(Boolean).sort().at(-1)||genAt();const codOrders=uniqueOrderCount(base.filter(isCodOrder)),waybillOrders=uniqueOrderCount(base.filter(r=>r.express_no||r.express_code));return intro('订单中心','以订单创建时间为主口径；销售金额来自销售事实，订单状态优先使用后台复查层并持续追到终态。')+`<section class="kpis orders-kpis"><div class="stat"><div class="stat-label">订单数</div><div class="stat-value">${M(uniqueOrderCount(base))}</div><div class="stat-note">当前筛选去重订单</div></div><div class="stat"><div class="stat-label">销售额</div><div class="stat-value">${M2(sum(base,['sales_sar']))}</div><div class="stat-note">SAR · 订单聚合金额</div></div><div class="stat"><div class="stat-label">COD 订单</div><div class="stat-value">${M(codOrders)}</div><div class="stat-note">来自 payment flag</div></div><div class="stat"><div class="stat-label">已关联物流</div><div class="stat-value">${M(waybillOrders)}</div><div class="stat-note">store + order_no 精确关联</div></div></section>${head('订单状态筛选',`按当前订单/履约字段自动归类；超过10天仍非终态的订单会进入后台复查，复查后仍未终态显示“平台未闭环”，并继续追踪。最近状态更新时间：${fmtStamp(maxUpdated)}。`,chips(['orders']))}<section class="panel order-center-panel">${orderStatusTabs(base)}${orderPager(S.orderPage,totalPages,active.length,pageSize)}${rs.length?orderTable(rs):'<div class="empty">当前状态筛选没有订单。</div>'}${orderPager(S.orderPage,totalPages,active.length,pageSize)}<p class="foot">一行一个 SHEIN 订单；多商品订单已在货号列汇总，搜索仍覆盖订单内所有货号 / SKC / 商品名。</p></section>`}

const RETURN_STATUS_FILTERS=[['all','全部'],['open','未闭环'],['waiting_buyer','待买家退货'],['in_transit','退货物流中'],['platform_pending','平台/仓库'],['settled','已落定'],['cancelled','已取消'],['cod','COD'],['quality','质量问题']];
const RETURN_RTV_FILTERS=[['all','全部RTV'],['received_resellable','已回仓可售'],['received_loss','已回仓损失'],['received_pending','已回仓待判'],['received_unknown','已回仓未知'],['not_received','未匹配回仓'],['not_applicable','无需退货包裹']];
function returnCaseId(r){return [sk(r),r?.aftersales_order_no||r?.return_order_no||r?.order_no||r?.skc||pkey(r),r?.request_time||dt(r)].join('|')}
function returnAmount(r){return firstNum(r,['amount_sar','price_amount_total','refund_amount_sar'])}
function returnQty(r){return firstNum(r,['quantity','return_quantity'])||1}
function returnStatusKey(r){return String(r?.status_group||'open').trim()||'open'}
function returnReasonGroup(r){return String(r?.reason_group||r?.reason_names||r?.reason||'未标注').trim()||'未标注'}
function returnRtvKey(r){return String(r?.rtv_group||'not_applicable').trim()||'not_applicable'}
function returnStatusLabel(r){return String(r?.status_group_label||RETURN_STATUS_FILTERS.find(x=>x[0]===returnStatusKey(r))?.[1]||'未落定')}
function returnRtvLabel(k){return ({received_resellable:'已回仓可售',received_loss:'已回仓损失',received_pending:'已回仓待判',received_unknown:'已回仓未知',not_received:'未匹配回仓',not_applicable:'无需退货包裹'}[k]||k||'—')}
function isCodReturn(r){if(r?.is_cod===true||r?.is_cod===1||String(r?.is_cod).toLowerCase()==='true')return true;const txt=[r?.payment_label,r?.payment_method,r?.reason_names,r?.reason_group].map(x=>String(x||'').toUpperCase()).join(' ');if(/NON[_ -]?COD/.test(txt))return false;return /(^|[^A-Z0-9])COD($|[^A-Z0-9])|货到付款/.test(txt)}
function isOpenReturn(r){return r?.is_open||!['settled','cancelled'].includes(returnStatusKey(r))}
function returnFilterMatch(r){if(S.returnStatus==='cod'&&!isCodReturn(r))return false;if(S.returnStatus==='quality'&&!/质量/.test(returnReasonGroup(r)))return false;if(S.returnStatus==='open'&&!isOpenReturn(r))return false;if(!['all','cod','quality','open'].includes(S.returnStatus)&&returnStatusKey(r)!==S.returnStatus)return false;if(S.returnReason&&S.returnReason!=='all'&&returnReasonGroup(r)!==S.returnReason)return false;if(S.returnRtv&&S.returnRtv!=='all'&&returnRtvKey(r)!==S.returnRtv)return false;return true}
function returnCounts(rows){return{cases:uniq(rows.map(returnCaseId)).length,amount:rows.reduce((a,r)=>a+returnAmount(r),0),qty:rows.reduce((a,r)=>a+returnQty(r),0),products:uniq(rows.map(pkey)).length,cod:uniq(rows.filter(isCodReturn).map(returnCaseId)).length,open:uniq(rows.filter(isOpenReturn).map(returnCaseId)).length,rtvReceived:uniq(rows.filter(r=>String(returnRtvKey(r)).startsWith('received')).map(returnCaseId)).length}}
function returnStatusBadge(r){const k=returnStatusKey(r);const cls=k==='settled'?'done':k==='cancelled'?'cancelled':k==='waiting_buyer'?'pending':k==='in_transit'?'shipped':k==='platform_pending'?'pending_recheck':'other';return`<span class="order-status ${H(cls)}">${H(returnStatusLabel(r))}</span>`}
function rtvBadge(r){const k=returnRtvKey(r);const cls=k==='received_resellable'?'done':k==='received_loss'?'abnormal':k==='received_pending'||k==='received_unknown'?'pending':k==='not_received'?'platform_unclosed':'other';return`<span class="order-status ${H(cls)}">${H(returnRtvLabel(k))}</span>`}
function returnTrend(rows,mode='request'){const m=new Map();for(const r of rows){const d=ISO(mode==='order'?(r.order_created_date||r.order_create_time):r.request_time)||dt(r);if(!d)continue;const row=m.get(d)||{date:d,value:0,cases:0,qty:0};row.value+=returnAmount(r);row.cases+=1;row.qty+=returnQty(r);m.set(d,row)}return Array.from(m.values()).sort((a,b)=>a.date.localeCompare(b.date)).map(r=>({...r,label:r.date}))}
function returnReasonOptions(rows){return Array.from(new Set(rows.map(returnReasonGroup).filter(Boolean))).sort((a,b)=>a.localeCompare(b,'zh-Hans-CN'))}
function returnStatusTabs(rows){const counts=new Map(RETURN_STATUS_FILTERS.map(([k])=>[k,0]));for(const [k] of RETURN_STATUS_FILTERS){counts.set(k,k==='all'?rows.length:rows.filter(r=>{const old=S.returnStatus;S.returnStatus=k;const ok=returnFilterMatch(r);S.returnStatus=old;return ok}).length)}return`<div class="status-tabs returns-tabs">${RETURN_STATUS_FILTERS.map(([k,label])=>`<button class="status-filter ${S.returnStatus===k?'active':''}" data-return-status="${H(k)}"><span>${H(label)}</span><b>${M(counts.get(k)||0)}</b></button>`).join('')}</div>`}
function returnPager(page,total,totalRows,pageSize){const prev=Math.max(1,page-1),next=Math.min(total,page+1);const sizes=[50,80,150,300];return`<div class="pager"><button class="btn" data-return-page="1" ${page<=1?'disabled':''}>首页</button><button class="btn" data-return-page="${prev}" ${page<=1?'disabled':''}>上一页</button><span>第 <input class="page-input" data-return-page-input type="number" min="1" max="${H(total)}" value="${H(page)}"> / <b>${M(total)}</b> 页</span><button class="btn" data-return-page="${next}" ${page>=total?'disabled':''}>下一页</button><button class="btn" data-return-page="${total}" ${page>=total?'disabled':''}>末页</button><label>每页 <select data-return-page-size>${sizes.map(n=>`<option value="${n}" ${Number(pageSize)===n?'selected':''}>${n}</option>`).join('')}</select> 条</label><span>共 ${M(totalRows)} 条售后</span></div>`}
function returnMiniChart(rows,mode,title){const data=returnTrend(rows,mode).slice(-45);if(!data.length)return'<div class="empty">当前筛选没有趋势数据。</div>';const top=Math.max(1,...data.map(r=>r.value));return`<div class="returns-mini-chart"><div class="mini-chart-head"><b>${H(title)}</b><span>${mode==='request'?'按售后申请时间':'按订单创建时间'} · 金额柱 / 单数提示</span></div><div class="mini-bars">${data.map(r=>`<div class="mini-bar" data-tip="${dataTip(`${r.date}\n金额：${M2(r.value)} SAR\n售后：${M(r.cases)} 单\n件数：${M(r.qty)} 件`)}" style="height:${Math.max(3,r.value/top*100)}%"><i></i><small>${H(String(r.date).slice(5))}</small></div>`).join('')}</div></div>`}
function returnRankCards(rows){const byProduct=Array.from(grp(rows,r=>pkey(r)||prod(r)),([key,x])=>({key,label:prod(x[0]),value:x.reduce((a,r)=>a+returnAmount(r),0),sub:`${M(x.length)} 单 · ${M(x.reduce((a,r)=>a+returnQty(r),0))} 件 · ${M(uniq(x.map(sk)).length)} 店`})).sort((a,b)=>b.value-a.value);
const byStore=Array.from(grp(rows,r=>sk(r)||'未知店铺'),([key,x])=>({key,label:storeDisplayName(key),value:x.reduce((a,r)=>a+returnAmount(r),0),sub:`${M(x.length)} 单 · ${M(x.reduce((a,r)=>a+returnQty(r),0))} 件`,color:ownByStore.get(key)?.color,ownerName:ownByStore.get(key)?.name||'',ownerColor:ownByStore.get(key)?.color||''})).sort((a,b)=>b.value-a.value);
const byReason=Array.from(grp(rows,returnReasonGroup),([key,x])=>({key,label:key,value:x.reduce((a,r)=>a+returnAmount(r),0),sub:`${M(x.length)} 单 · ${M(x.reduce((a,r)=>a+returnQty(r),0))} 件`})).sort((a,b)=>b.value-a.value);
return`<section class="rank-grid returns-rank-grid"><div class="panel rank-panel"><h4>原因金额排行</h4><p class="sub">按售后申请金额排序，点击后可在上方筛选原因。</p>${homeRankList(byReason,{limit:12,color:()=> '#ef4444',attr:it=>`data-return-reason="${H(it.key)}"`,className:'returns-rank'})}</div><div class="panel rank-panel"><h4>货号售后排行</h4><p class="sub">定位异常货号；金额为申请口径，不等同最终损失。</p>${homeRankList(byProduct,{limit:12,color:()=> '#f97316',attr:it=>`data-home-product="${H(it.key)}"`,className:'returns-rank'})}</div><div class="panel rank-panel"><h4>店铺售后排行</h4><p class="sub">保留负责人色块，便于分组复盘。</p>${homeRankList(byStore,{limit:12,showOwner:true,color:it=>it.color||'#7357ff',attr:it=>`data-home-store="${H(it.key)}"`,className:'returns-rank'})}</div></section>`}
function returnQueue(rows){const open=rows.filter(isOpenReturn).sort((a,b)=>(N(b.open_days)-N(a.open_days))||(returnAmount(b)-returnAmount(a))).slice(0,24);return`<section class="panel returns-queue"><h4>未闭环售后队列</h4><p class="sub">只展示需要继续跟进的售后，不把“未闭环”直接当最终损失；RTV/ET 有证据时会显示回仓去向。</p>${open.length?table(['打开天数','店铺','售后/订单','货号','金额','状态','RTV/ET','建议动作'],open.map(r=>[M(N(r.open_days))+' 天',storeDisplayName(sk(r)),`<b class="mono">${H(r.aftersales_order_no||r.return_order_no||r.order_no||'—')}</b><small>${H(r.order_no||'')}</small>`,prod(r),M2(returnAmount(r)),returnStatusBadge(r),rtvBadge(r),`<span class="note">${H(r.next_action||'结合货号、店铺和原因排行复核。')}</span>`])):'<div class="empty">当前筛选没有未闭环售后。</div>'}</section>`}
function returnDetailTable(rows){return`<div class="table-wrap returns-table-wrap"><table class="returns-table"><colgroup><col class="c-time"><col class="c-store"><col class="c-order"><col class="c-product"><col class="c-num"><col class="c-status"><col class="c-status"><col class="c-reason"><col class="c-action"></colgroup><thead><tr><th>申请时间</th><th>店铺</th><th>售后 / 订单</th><th>货号 / SKC</th><th class="num">金额</th><th>售后状态</th><th>RTV/ET</th><th>原因</th><th>建议动作</th></tr></thead><tbody>${rows.map(r=>{const tip=dataTip([`售后单：${r.aftersales_order_no||'—'}`,`退货单：${r.return_order_no||'—'}`,`订单：${r.order_no||'—'}`,`付款：${r.payment_label||r.payment_method||'—'}`,`RTV：${returnRtvLabel(returnRtvKey(r))}`,r.rtv_trace_status?`RTV状态：${r.rtv_trace_status}`:'',r.et_return_order_ids?`ET退货单：${r.et_return_order_ids}`:'',r.destination_summary?`去向：${r.destination_summary}`:''].filter(Boolean).join('\n'));return`<tr><td><b>${H(shortDate(r.request_time||dt(r)))}</b><small>${H(fmtStamp(r.request_time).replace(/^.*? /,''))}</small></td><td>${H(storeDisplayName(sk(r)))}</td><td><b class="mono">${H(r.aftersales_order_no||r.return_order_no||'—')}</b><small class="mono">${H(r.order_no||'')}</small>${isCodReturn(r)?'<small><span class="cod-badge">COD</span></small>':''}</td><td><b>${H(prod(r))}</b><small>${H(r.skc||r.goods_title||'')}</small></td><td class="num"><b>${M2(returnAmount(r))}</b><small>SAR · ${M(returnQty(r))} 件</small></td><td>${returnStatusBadge(r)}<small>${H(String(r.order_sub_status_name||r.return_package_status_name||'').trim())}</small></td><td data-tip="${tip}">${rtvBadge(r)}<small>${H([r.rtv_trace_status,r.et_return_order_ids,r.rtv_latest_received_time&&shortDate(r.rtv_latest_received_time)].filter(Boolean).join(' · ')||'无退货包裹/未匹配')}</small></td><td><b>${H(returnReasonGroup(r))}</b><small>${H(r.reason_names||r.resolution_plan_name||'')}</small></td><td><span class="note">${H(r.next_action||'结合排行复核。')}</span></td></tr>`}).join('')}</tbody></table></div>`}
function returnsPage(){ensure('returns',true);if(!A(D.afterSales).length&&SS.afterSales?.status!=='ok')return intro('退货退款中心','按售后申请时间和订单创建时间双口径拆解售后。')+wait('afterSales');
const base=returns().slice().sort((a,b)=>String(b.request_time||dt(b)).localeCompare(String(a.request_time||dt(a))));const filtered=base.filter(returnFilterMatch);const pageSize=Math.max(20,Math.min(500,Number(S.returnPageSize)||80)),totalPages=Math.max(1,Math.ceil(filtered.length/pageSize));S.returnPage=Math.min(Math.max(1,Number(S.returnPage)||1),totalPages);const start=(S.returnPage-1)*pageSize,rs=filtered.slice(start,start+pageSize);const all=returnCounts(base),cur=returnCounts(filtered);const salesBase=salesSummary();const refundRatio=salesBase.net?cur.amount/salesBase.net:null;const avgOpenRows=filtered.filter(isOpenReturn);const avgOpen=avgOpenRows.length?avgOpenRows.reduce((a,r)=>a+N(r.open_days),0)/avgOpenRows.length:0;const reasons=returnReasonOptions(base);const rtvWithTrace=base.filter(r=>returnRtvKey(r)!=='not_applicable'&&returnRtvKey(r)!=='not_received').length;const dataNote=`当前筛选 ${M(cur.cases)} 单 / ${M(cur.qty)} 件；申请金额/同期净销售比 ${refundRatio==null?'—':PCT(refundRatio)}。这是期间申请口径，不是 cohort 退货率。`;
return intro('退货退款中心','把售后申请、订单创建口径、COD/物流异常、RTV/ET 回仓和未闭环队列放在一起复盘；不把申请金额直接当最终损失。')+`<section class="kpis returns-kpis"><div class="stat"><div class="stat-label">售后申请金额</div><div class="stat-value">${M2(cur.amount)}</div><div class="stat-note">SAR · ${H(selectedRangeText())}</div></div><div class="stat"><div class="stat-label">售后单 / 件数</div><div class="stat-value">${M(cur.cases)} / ${M(cur.qty)}</div><div class="stat-note">当前筛选；全量 ${M(all.cases)} 单</div></div><div class="stat"><div class="stat-label">未闭环</div><div class="stat-value">${M(cur.open)}</div><div class="stat-note">平均打开 ${avgOpen?M2(avgOpen):'0'} 天</div></div><div class="stat"><div class="stat-label">COD / RTV</div><div class="stat-value">${M(cur.cod)} / ${M(cur.rtvReceived)}</div><div class="stat-note">COD 售后 / 已回仓记录；RTV线索 ${M(rtvWithTrace)}</div></div></section>${head('售后筛选与口径',dataNote,chips(['afterSales','orders','homeRankings']))}<section class="panel returns-filter-panel">${returnStatusTabs(base)}<div class="returns-filter-row"><label>原因 <select data-return-reason-select><option value="all">全部原因</option>${reasons.map(x=>`<option value="${H(x)}" ${S.returnReason===x?'selected':''}>${H(x)}</option>`).join('')}</select></label><label>RTV/ET <select data-return-rtv-select>${RETURN_RTV_FILTERS.map(([k,l])=>`<option value="${H(k)}" ${S.returnRtv===k?'selected':''}>${H(l)}</option>`).join('')}</select></label><button class="btn" data-return-clear="1">清空售后筛选</button><span class="note">申请金额/销售比只用于异常发现；最终退货率需要按订单创建 cohort 成熟窗口复盘。</span></div></section><section class="grid two returns-trends"><div class="panel">${returnMiniChart(filtered,'request','售后申请趋势')}</div><div class="panel">${returnMiniChart(filtered,'order','订单创建口径趋势')}</div></section>${returnRankCards(filtered)}${returnQueue(filtered)}<section class="panel returns-detail-panel"><h4>售后明细</h4><p class="sub">分页渲染全部筛选结果，搜索框可搜货号、SKC、订单号、售后单、退货物流和 ET 单号。</p>${returnPager(S.returnPage,totalPages,filtered.length,pageSize)}${rs.length?returnDetailTable(rs):'<div class="empty">当前筛选没有售后记录。</div>'}${returnPager(S.returnPage,totalPages,filtered.length,pageSize)}</section>`}

function pmatrix(){const map=new Map();
const en=(k,n)=>{k=k||n||'-';if(!map.has(k))map.set(k,{key:k,name:n||k,stores:new Map(),tot:{wait:0,on:0,sold:0,off:0}});return map.get(k)};for(const r of matrix()){const p=en(pkey(r),prod(r)),s=sk(r);if(!s)continue;
const c=p.stores.get(s)||{wait:0,on:0,sold:0,off:0};c.wait+=N(r.wait_shelf_count);c.on+=N(r.on_shelf_count);c.sold+=N(r.sold_out_count);c.off+=N(r.out_shelf_count||r.off_shelf_count);p.stores.set(s,c)}for(const r of links()){const p=en(pkey(r),prod(r)),s=sk(r);if(!s)continue;
const c=p.stores.get(s)||{wait:0,on:0,sold:0,off:0},st=String(r.shelf_status_name||r.health_bucket||'').toLowerCase();if(r.is_wait_shelf||/待上架/.test(st))c.wait++;else if(r.is_on_shelf||/已上架|上架/.test(st))c.on++;else if(/售罄/.test(st))c.sold++;else if(/下架|淘汰|退役/.test(st))c.off++;p.stores.set(s,c)}for(const p of map.values())for(const c of p.stores.values()){p.tot.wait+=c.wait;p.tot.on+=c.on;p.tot.sold+=c.sold;p.tot.off+=c.off}return Array.from(map.values()).filter(p=>p.tot.wait+p.tot.on+p.tot.sold+p.tot.off>0).sort((a,b)=>(b.tot.on+b.tot.wait)-(a.tot.on+a.tot.wait)).slice(0,120)}

function productsPage(){ensure('products',true);if(!A(D.matrix).length&&!A(D.storeLinks).length&&SS.linksData?.status!=='ok')return intro('商品列表','标准货号 × 店铺，上架状态矩阵。')+wait('linksData');
const rs=pmatrix(),st=stores.filter(x=>S.scope==='ALL'?true:scopeStores().has(x));
const body=rs.length?`<div class="table-wrap"><div class="status-grid" style="--cols:${st.length}"><div class="cell headcell">标准货号</div>${st.map(s=>`<div class="cell headcell">${H(s)}</div>`).join('')}${rs.map(p=>`<div class="cell product">${H(p.name)}<div class="tiny">待 ${p.tot.wait} · 上 ${p.tot.on} · 售罄 ${p.tot.sold} · 下 ${p.tot.off}</div></div>${st.map(s=>{const c=p.stores.get(s)||{wait:0,on:0,sold:0,off:0};return`<div class="cell"><div class="counts"><span class="wait" title="待上架">${c.wait}</span><span class="on" title="已上架">${c.on}</span><span class="sold" title="已售罄">${c.sold}</span><span class="off" title="已下架">${c.off}</span></div></div>`}).join('')}`).join('')}</div></div>`:'<div class="empty">当前筛选没有商品链接状态。</div>';return intro('商品列表','参考 SHEIN 商品列表：按标准货号归并，横向看每个店待上架、已上架、已售罄、已下架数量。')+head('上架状态矩阵','每格四个数依次为：待上架 / 已上架 / 已售罄 / 已下架。',chips(['linksData']))+`<section class="panel">${body}</section>`}

function inventoryPage(){ensure('inventory',true);
const ps=invProducts().slice().sort((a,b)=>N(a.days_of_supply_with_incoming)-N(b.days_of_supply_with_incoming));
const tr=trendFirst(invTrend(),['platform_display_stock','usable_inventory','inventory_quantity']);return intro('库存管理','分清三套口径：前台展示库存趋势、ET 可售、成本表供给与去化周期。')+`<section class="kpis"><div class="stat"><div class="stat-label">ET可售</div><div class="stat-value">${M(sum(ps,['et_estimated_available_qty']))}</div><div class="stat-note">ET 货代仓可售估算</div></div><div class="stat"><div class="stat-label">成本表在库</div><div class="stat-value">${M(sum(ps,['estimated_on_hand_quantity']))}</div><div class="stat-note">到仓批次 - 已售</div></div><div class="stat"><div class="stat-label">成本表在途</div><div class="stat-value">${M(sum(ps,['incoming_quantity']))}</div><div class="stat-note">已发未到/待确认</div></div><div class="stat"><div class="stat-label">成本表供给</div><div class="stat-value">${M(sum(ps,['estimated_total_supply_quantity']))}</div><div class="stat-note note">成本表供给 = 到仓 + 在途 - 已售；不等于 ET可售 + 在途。</div></div></section>${head('库存趋势','来自前台展示库存快照；进入库存页才按需加载。',chips(['inventoryTrend']))}<section class="panel">${invTrend().length?chart(tr):wait('inventoryTrend','正在加载云端库存趋势 section…')}</section>`+panel('去化周期','按成本表供给和近 7/30 天速度估算。备注保持小字号。',['货号','ET可售','成本表在库','在途','成本表供给','近30天销量','去化周期','说明'],ps.slice(0,200).map(r=>[prod(r),M(r.et_estimated_available_qty),M(r.estimated_on_hand_quantity),M(r.incoming_quantity),M(r.estimated_total_supply_quantity),M(r.gross_sold_30d),M2(r.days_of_supply_with_incoming||r.days_of_supply_on_hand),`<span class="note">${H(r.stock_status||r.risk_level||'')}</span>`]))}

function trafficPage(){ensure('traffic',true);if(!A(D.productTrafficDaily).length&&SS.productTrafficDaily?.status!=='ok')return intro('流量数据','目标粒度：日期 × 店铺 × 标准货号。')+wait('productTrafficDaily','正在加载云端货号级每日流量 section…');
const rs=traffic(),by=Array.from(grp(rs,r=>pkey(r)),([key,x])=>({key,label:prod(x[0]),value:sumFirst(x,['eps_uv','exposure_uv','exposure_cnt']),sub:`访客 ${M(sumFirst(x,['goods_uv','uv','visitor_cnt']))} · 成交 ${M(sumFirst(x,['sale_cnt','pay_order_cnt','quantity']))}`})).sort((a,b)=>b.value-a.value);
const exp=sumFirst(rs,['eps_uv','exposure_uv','exposure_cnt']),uv=sumFirst(rs,['goods_uv','uv','visitor_cnt']),pay=sumFirst(rs,['sale_cnt','pay_order_cnt','quantity']);return intro('流量数据','货号级每日流量必须精确到日期 × 店铺 × 标准货号，并在当前筛选下重算曝光、访客、成交和转化。')+`<section class="kpis"><div class="stat"><div class="stat-label">曝光</div><div class="stat-value">${M(exp)}</div><div class="stat-note">当前筛选汇总</div></div><div class="stat"><div class="stat-label">访客</div><div class="stat-value">${M(uv)}</div><div class="stat-note">点击率 ${exp?PCT(uv/exp):'—'}</div></div><div class="stat"><div class="stat-label">成交件数</div><div class="stat-value">${M(pay)}</div><div class="stat-note">支付率 ${uv?PCT(pay/uv):'—'}</div></div><div class="stat"><div class="stat-label">明细粒度</div><div class="stat-value">${M(rs.length)}</div><div class="stat-note note">每行应对应日期 × 店铺 × 标准货号；大表按需加载，不拖慢首页。</div></div></section>${head('每日曝光趋势','只保留一个图，绝对量趋势和比例指标分开看。',chips(['productTrafficDaily']))}<section class="panel">${chart(trendFirst(rs,['eps_uv','exposure_uv','exposure_cnt']))}</section><section class="grid two"><div class="panel"><h4>货号流量排行</h4>${rank(by,'product')}</div><div>${panel('流量明细','默认展示 300 行。',['日期','店铺','货号','曝光','访客','成交','点击率','支付率'],rs.slice(0,300).map(r=>[dt(r),sk(r),prod(r),M(firstNum(r,['eps_uv','exposure_uv','exposure_cnt'])),M(firstNum(r,['goods_uv','uv','visitor_cnt'])),M(firstNum(r,['sale_cnt','pay_order_cnt','quantity'])),PCT(N(r.click_rate)||(N(r.goods_uv)/Math.max(1,N(r.eps_uv)))),PCT(N(r.pay_rate)||(N(r.sale_cnt)/Math.max(1,N(r.goods_uv))))]))}</div></section>`}
function reviewsPage(){ensure('reviews',true);if(!A(D.comments).length&&SS.comments?.status!=='ok')return intro('商品评价','低星、质量投诉、中文译文。')+wait('comments');
const rs=F(D.comments||[]).slice().sort((a,b)=>String(dt(b)).localeCompare(dt(a))).slice(0,300);return intro('商品评价','按货号和店铺定位差评、质量投诉和说明书/物流问题。')+panel('评价明细','优先展示平台中文译文。',['日期','店铺','货号','星级','中文译文','原文'],rs.map(r=>[dt(r),sk(r),prod(r),r.goods_comment_star_name||r.goods_comment_star,r.goods_comment_content_zh||'',r.goods_comment_content||'']))}

function actionCard(a){return`<div class="action"><div class="tags"><span class="tag ${/高|high/i.test(String(a.priority))?'danger':''}">${H(a.priority||'优先级')}</span><span class="tag">${H(sk(a)||'-')}</span><span class="tag">${H(a.action_domain||a.category||'动作')}</span></div><h4>${H(a.title||prod(a))}</h4><p class="note">${H(a.reason||a.evidence||'')}</p><div class="tiny">${H(prod(a))} · ${H(a.next_step||'')}</div></div>`}

function marketingPage(){ensure('marketing',true);
const rs=links().filter(r=>r.activity_label||r.performance_activity_names||r.performance_activity_tag).slice(0,300);
const as=actions().filter(r=>/marketing|营销|活动|coupon|价格|价/i.test([r.action_domain,r.category,r.title,r.reason].join(' ')));return intro('营销中心','把活动报名、优惠券、限时折扣、价格栈和利润率放到一个复核中心。')+`<section class="grid two"><div class="panel"><h4>当前营销承接</h4><p class="sub">来自链接/表现标签，后续扩展为活动报名矩阵和最终利润率。</p>${rs.length?table(['店铺','货号','SKC','活动标签','活动名称','质量层级'],rs.map(r=>[sk(r),prod(r),r.skc,r.activity_label||r.performance_activity_tag||'',r.performance_activity_names||'',r.quality_grade||r.performance_total_quality_level||''])):'<div class="empty">当前筛选没有营销标签。</div>'}</div><div class="panel"><h4>营销动作</h4><p class="sub">真实报名/改价仍需 dry-run、复核、授权执行、live 回读。</p>${as.length?as.slice(0,24).map(actionCard).join(''):'<div class="empty">当前筛选没有营销动作。</div>'}</div></section>`}

function opsPage(){ensure('ops',true);
const as=actions().slice().sort((a,b)=>N(b.score)-N(a.score));return intro('自动化运营','合并链接管理中台和动作池：一个会话、一个任务、一个动作状态。')+`<section class="grid three"><div class="stat"><div class="stat-label">待处理动作</div><div class="stat-value">${M(as.length)}</div><div class="stat-note">当前筛选</div></div><div class="stat"><div class="stat-label">高优先级</div><div class="stat-value">${M(as.filter(a=>/高|high/i.test(String(a.priority))).length)}</div><div class="stat-note">需要优先复核</div></div><div class="stat"><div class="stat-label">执行边界</div><div class="stat-value">Dry-run</div><div class="stat-note note">真实上下架/改价/报名不静默提交。</div></div></section>${head('统一动作工作台','后续自动运营系统从这里进入；当前第一版先重组信息和状态。',chips(['actions','linksData']))}<section class="grid two"><div class="panel"><h4>动作队列</h4>${as.length?as.slice(0,60).map(actionCard).join(''):'<div class="empty">当前筛选没有动作。</div>'}</div><div class="panel"><h4>动作生命周期</h4><p class="note">1. 建议：由 BI/规则发现机会或风险。<br>2. 预检：读取链接、库存、价格、证据。<br>3. 用户确认：展示影响范围和回滚方式。<br>4. 执行：调用受控接口。<br>5. 回读：确认 SHEIN 后台真实状态并写审计。</p><div class="empty">这里后续承接自然语言任务、素材、执行步骤和审计日志。</div></div></section>`}

function systemPage(){const secs=Object.keys(SL);return intro('系统健康','展示云端运行态、section 加载状态和数据新鲜度边界。')+`<section class="grid three"><div class="stat"><div class="stat-label">Core generatedAt</div><div class="stat-value" style="font-size:18px">${H(genAt()||'—')}</div><div class="stat-note">来自云端运行态 core</div></div><div class="stat"><div class="stat-label">Core 加载</div><div class="stat-value">${H(S.core)}</div><div class="stat-note">${H(S.err||'正常')}</div></div><div class="stat"><div class="stat-label">Section</div><div class="stat-value">${M(secs.filter(s=>SS[s]?.status==='ok').length)}/${secs.length}</div><div class="stat-note">按需加载状态</div></div></section><section class="panel"><h4>Section 状态</h4>${chips(secs)}<p class="foot">数据判断只认云端运行态；仓库快照仅作页面启动兼容。</p></section>`}

function shell(){document.getElementById('nav').innerHTML=TABS.map(t=>`<button class="${S.tab===t[0]?'active':''}" data-tab="${t[0]}"><span>${t[1]}</span><small>${t[2]}</small></button>`).join('');$('scope').innerHTML=`<option value="ALL">全部店铺</option>`+owners.map(g=>`<option value="OWNER:${H(g.key)}">${H(ownerOptionLabel(g))}</option>`).join('')+stores.map(s=>`<option value="${H(s)}">${H(s)} · ${H(smeta.get(s)?.companyName||'')}</option>`).join('');sync(false);const rd=$('rangeDock');if(rd)rd.innerHTML=rangeControl();$('crumb').textContent=`${(TABS.find(t=>t[0]===S.tab)||TABS[0])[1]} · ${scopeName()} · ${selectedRangeText()}`;const ss=$('sideStatus');if(ss)ss.innerHTML=sideStatusHtml()}

function sync(read=true){if(read){S.q=$('q')?.value||'';S.scope=$('scope')?.value||'ALL'}if($('q'))$('q').value=S.q;if($('scope'))$('scope').value=S.scope}

function render(){hideChartTip();shell();if(S.core==='loading'){$('view').innerHTML='<div class="loading"><span class="spin"></span><span>正在连接云端 BI runtime…</span></div>';return}if(S.core==='error'){$('view').innerHTML=`<div class="error"><b>云端 BI runtime 连接失败</b><br>${H(S.err)}<p><button class="btn" id="retryCore">重试</button></p></div>`;return}const map={home,orders:ordersPage,returns:returnsPage,products:productsPage,inventory:inventoryPage,traffic:trafficPage,reviews:reviewsPage,marketing:marketingPage,ops:opsPage,system:systemPage};$('view').innerHTML=(map[S.tab]||home)()}

function rerenderWithEnsure(){sync(false);render();ensure(S.tab,true)}
function setRangeDate(role,date){if(!date)return;if(role==='end'){S.end=date;S.calendarEndMonth=calendarMonthStart(date)}else{S.start=date;S.calendarStartMonth=calendarMonthStart(date)}if(S.start&&S.end&&S.start>S.end){const t=S.start;S.start=S.end;S.end=t}S.rangePreset='custom';S.rangeOpen=true;S.orderPage=1;rerenderWithEnsure()}

document.addEventListener('click',e=>{const b=e.target.closest('button');if(!e.target.closest('#rangeDock')&&S.rangeOpen){S.rangeOpen=false;render()}if(!b)return;if(b.dataset.tab){S.tab=b.dataset.tab;render();ensure(S.tab,true);return}if(b.dataset.jump){S.tab=b.dataset.jump;render();ensure(S.tab,true);return}if(b.dataset.trendMetric){S.trendMetric=b.dataset.trendMetric;S.metric=S.trendMetric;render();ensure(S.tab,true);return}if(b.dataset.metric){S.trendMetric=b.dataset.metric;S.metric=b.dataset.metric;render();ensure(S.tab,true);return}if(b.dataset.preset){preset(Number(b.dataset.preset));return}if(b.dataset.rangePreset){applyPreset(b.dataset.rangePreset);rerenderWithEnsure();return}if(b.dataset.rangeToggle){S.rangeOpen=!S.rangeOpen;render();return}if(b.dataset.calendarDate){setRangeDate(b.dataset.calendarRole||'start',b.dataset.calendarDate);return}if(b.dataset.calendarShift){const role=b.dataset.calendarShift,delta=Number(b.dataset.calendarDelta||0);S.rangeOpen=true;if(role==='end')S.calendarEndMonth=addCalendarMonths(S.calendarEndMonth||S.end,delta);else S.calendarStartMonth=addCalendarMonths(S.calendarStartMonth||S.start,delta);render();return}if(b.dataset.load){load(b.dataset.load,false,true);return}if(b.dataset.orderStatus){S.orderStatus=b.dataset.orderStatus;S.orderPage=1;render();ensure(S.tab,true);return}if(b.dataset.returnStatus){S.returnStatus=b.dataset.returnStatus;S.returnPage=1;render();ensure(S.tab,true);return}if(b.dataset.returnPage){S.returnPage=Number(b.dataset.returnPage)||1;render();return}if(b.dataset.returnReason){S.returnReason=b.dataset.returnReason;S.returnPage=1;render();return}if(b.dataset.returnClear){S.returnStatus='all';S.returnReason='all';S.returnRtv='all';S.returnPage=1;render();return}if(b.dataset.orderPage){S.orderPage=Number(b.dataset.orderPage)||1;render();return}if(b.dataset.homeStore){S.scope=b.dataset.homeStore;S.q='';S.orderPage=1;S.returnPage=1;rerenderWithEnsure();return}if(b.dataset.homeProduct){S.q=b.dataset.homeProduct;S.orderPage=1;S.returnPage=1;rerenderWithEnsure();return}if(b.id==='clearFilters'){S.q='';S.scope='ALL';S.orderPage=1;S.returnPage=1;S.returnStatus='all';S.returnReason='all';S.returnRtv='all';applyPreset('today');rerenderWithEnsure();return}if(b.id==='retryCore'){core();return}});
function chartTipEl(){let el=$('chartTooltip');if(!el){el=document.createElement('div');el.id='chartTooltip';el.className='chart-tooltip';document.body.appendChild(el)}return el}
function hideChartTip(){const el=$('chartTooltip');if(el)el.classList.remove('visible')}
function showChartTip(e,target){const text=target?.getAttribute('data-tip')||'';if(!text)return hideChartTip();const el=chartTipEl();el.textContent=text;const pad=14,w=260,h=120;let x=e.clientX+pad,y=e.clientY+pad;if(x+w>window.innerWidth)x=Math.max(12,e.clientX-w-pad);if(y+h>window.innerHeight)y=Math.max(12,e.clientY-h-pad);el.style.left=x+'px';el.style.top=y+'px';el.classList.add('visible')}
document.addEventListener('mousemove',e=>{const t=e.target?.closest?.('[data-tip]');if(t)showChartTip(e,t);else hideChartTip()});
document.addEventListener('mouseleave',hideChartTip,true);
document.addEventListener('keydown',e=>{if(e.target?.dataset?.orderPageInput!==undefined&&e.key==='Enter'){S.orderPage=Number(e.target.value)||1;render()}if(e.target?.dataset?.returnPageInput!==undefined&&e.key==='Enter'){S.returnPage=Number(e.target.value)||1;render()}});
document.addEventListener('input',e=>{if(e.target?.id==='q'){S.q=e.target.value||'';S.orderPage=1;S.returnPage=1;render();ensure(S.tab,true)}});
document.addEventListener('change',e=>{if(e.target?.id==='scope'){S.scope=e.target.value||'ALL';S.orderPage=1;S.returnPage=1;render();ensure(S.tab,true);return}if(e.target?.dataset?.orderPageInput!==undefined){S.orderPage=Number(e.target.value)||1;render();return}if(e.target?.dataset?.orderPageSize!==undefined){S.orderPageSize=Number(e.target.value)||80;S.orderPage=1;render();return}if(e.target?.dataset?.returnPageInput!==undefined){S.returnPage=Number(e.target.value)||1;render();return}if(e.target?.dataset?.returnPageSize!==undefined){S.returnPageSize=Number(e.target.value)||80;S.returnPage=1;render();return}if(e.target?.dataset?.returnReasonSelect!==undefined){S.returnReason=e.target.value||'all';S.returnPage=1;render();return}if(e.target?.dataset?.returnRtvSelect!==undefined){S.returnRtv=e.target.value||'all';S.returnPage=1;render();return}if(e.target?.id==='rangeStart'){const d=ISO(e.target.value);if(d)setRangeDate('start',d);return}if(e.target?.id==='rangeEnd'){const d=ISO(e.target.value);if(d)setRangeDate('end',d);return}});
core();})()
