#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath, pathToFileURL} from 'node:url';
import {createRequire} from 'node:module';
const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const REPORT_DIR = path.join(ROOT, 'outputs', 'reports');
const PROFILE_DIR = path.join(ROOT, 'profiles', 'persistent-feishu-profile');
const BASE_TOKEN='SnnQbrAu6aLzMWsnEICcy0cKnJh', DASHBOARD_ID='blkFn3qHrwdsrJyX';
function loadPlaywright(){try{return createRequire(import.meta.url)('playwright')}catch{} const b=path.join(process.env.USERPROFILE||'', '.cache','codex-runtimes','codex-primary-runtime','dependencies','node','node_modules','playwright','index.js'); return createRequire(pathToFileURL(b))(b)}
function chromeExecutablePath(){for(const p of [process.env.CHROME_PATH,'C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe','C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe'].filter(Boolean)){try{if(createRequire(import.meta.url)('node:fs').existsSync(p))return p}catch{}}}
async function openCustom(page,titleText){await page.goto(`https://zcnm3ts63aph.feishu.cn/base/${BASE_TOKEN}?table=${DASHBOARD_ID}`,{waitUntil:'domcontentloaded'}); await page.waitForLoadState('networkidle',{timeout:30000}).catch(()=>{}); await page.waitForTimeout(5000); const rect=await page.evaluate(titleText=>{const item=[...document.querySelectorAll('.layout-item')].find(el=>(el.innerText||'').includes(titleText)); if(!item)return null; item.scrollIntoView({block:'center',inline:'center'}); const r=item.getBoundingClientRect(); return {x:r.x,y:r.y,w:r.width,h:r.height}}, titleText); if(!rect) throw new Error('card not found'); await page.waitForTimeout(1000); const r=await page.evaluate(titleText=>{const item=[...document.querySelectorAll('.layout-item')].find(el=>(el.innerText||'').includes(titleText)); const r=item.getBoundingClientRect(); return {x:r.x,y:r.y,w:r.width,h:r.height}}, titleText); await page.mouse.move(r.x+r.w-36,r.y+30); await page.waitForTimeout(200); await page.mouse.click(r.x+r.w-31,r.y+30); await page.waitForTimeout(400); await page.getByText('配置',{exact:true}).click(); await page.waitForTimeout(1500); await page.getByText('自定义配置',{exact:true}).click(); await page.waitForTimeout(1000)}
async function main(){await fs.mkdir(REPORT_DIR,{recursive:true}); const {chromium}=loadPlaywright(); const browser=await chromium.launchPersistentContext(PROFILE_DIR,{headless:true,executablePath:chromeExecutablePath(),viewport:{width:1800,height:1200},locale:'zh-CN',args:['--disable-gpu','--disable-dev-shm-usage','--disable-features=Translate','--no-first-run','--no-default-browser-check']}); try{const page=browser.pages()[0]||await browser.newPage(); page.setDefaultTimeout(90000); await openCustom(page,'今日动销产品数（DSY）'); const which=process.argv.includes('--text')?'文字颜色':'背景颜色'; const clicked=await page.evaluate(which=>{const labels=[...document.querySelectorAll('p,div,span')].filter(el=>(el.innerText||'').trim()===which); const label=labels[labels.length-1]; if(!label)return false; let box=label.closest('.dashboard-chart-block-setting-panel-tab-pane-item')||label.parentElement; let sel=box?.querySelector('.ud__select__selector, [role=combobox]'); if(!sel){let next=box; for(let i=0;next&&i<5;i++,next=next.nextElementSibling){sel=next.querySelector?.('.ud__select__selector, [role=combobox]'); if(sel)break}} if(!sel)return false; const r=sel.getBoundingClientRect(); sel.dispatchEvent(new MouseEvent('mousedown',{bubbles:true,clientX:r.x+r.width/2,clientY:r.y+r.height/2})); sel.dispatchEvent(new MouseEvent('mouseup',{bubbles:true,clientX:r.x+r.width/2,clientY:r.y+r.height/2})); sel.dispatchEvent(new MouseEvent('click',{bubbles:true,clientX:r.x+r.width/2,clientY:r.y+r.height/2})); return true}, which); await page.waitForTimeout(1000); const shot=path.join(REPORT_DIR,`dashboard-color-options-${which}-${Date.now()}.png`); await page.screenshot({path:shot,fullPage:false}); const info=await page.evaluate(()=>[...document.querySelectorAll('body *')].map(el=>{const r=el.getBoundingClientRect();const s=getComputedStyle(el); if(r.width<=0||r.height<=0||s.display==='none'||s.visibility==='hidden')return null; const text=(el.innerText||el.getAttribute('aria-label')||el.getAttribute('title')||'').trim(); if(!text)return null; if(!/(默认|蓝|橙|绿|红|紫|黄|背景|文字|颜色|自定义|浅|深)/.test(text))return null; return {tag:el.tagName,text:text.slice(0,200),cls:String(el.className||'').slice(0,160),rect:{x:r.x,y:r.y,w:r.width,h:r.height},bg:s.backgroundColor,color:s.color}}).filter(Boolean)); const out=path.join(REPORT_DIR,'dashboard-color-options-explore.json'); await fs.writeFile(out,JSON.stringify({clicked,which,screenshot:path.relative(ROOT,shot),info},null,2),'utf8'); console.log(JSON.stringify({ok:true,clicked,which,screenshot:path.relative(ROOT,shot),out:path.relative(ROOT,out),sample:info.slice(-80)},null,2))}finally{await browser.close()}}
main().catch(e=>{console.error(JSON.stringify({ok:false,error:e.message},null,2));process.exit(1)});
