#!/usr/bin/env python3
"""Render controlled SHEIN QA charts as PNG for the Lark sales QA bot.

The input is a small JSON chart spec generated by scripts/lark_sales_qa_bot.mjs.
This renderer intentionally supports only simple, auditable BI charts.
"""

from __future__ import annotations

import argparse
import json
import math
import os
from pathlib import Path

from PIL import Image, ImageDraw, ImageFont


FONT_CANDIDATES = [
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Regular.ttc",
    "/usr/share/fonts/opentype/noto/NotoSerifCJK-Regular.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "C:/Windows/Fonts/msyh.ttc",
    "C:/Windows/Fonts/simhei.ttf",
]

BOLD_FONT_CANDIDATES = [
    "/usr/share/fonts/opentype/noto/NotoSansCJK-Bold.ttc",
    "/usr/share/fonts/truetype/noto/NotoSansCJK-Bold.ttc",
    "/usr/share/fonts/opentype/noto/NotoSerifCJK-Bold.ttc",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "C:/Windows/Fonts/msyhbd.ttc",
    "C:/Windows/Fonts/simhei.ttf",
]


def load_font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont | ImageFont.ImageFont:
    for font_path in (BOLD_FONT_CANDIDATES if bold else FONT_CANDIDATES):
        if os.path.exists(font_path):
            try:
                return ImageFont.truetype(font_path, size)
            except Exception:
                continue
    return ImageFont.load_default()


def text_width(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.ImageFont) -> int:
    if not text:
        return 0
    box = draw.textbbox((0, 0), text, font=font)
    return max(0, box[2] - box[0])


def ellipsize(draw: ImageDraw.ImageDraw, text: str, font: ImageFont.ImageFont, max_width: int) -> str:
    text = str(text or "")
    if text_width(draw, text, font) <= max_width:
        return text
    suffix = "…"
    lo, hi = 0, len(text)
    while lo < hi:
        mid = (lo + hi + 1) // 2
        candidate = text[:mid] + suffix
        if text_width(draw, candidate, font) <= max_width:
            lo = mid
        else:
            hi = mid - 1
    return text[:lo] + suffix


def fmt_number(value: float, unit: str = "") -> str:
    if not math.isfinite(value):
        value = 0
    if abs(value) >= 100:
        body = f"{value:,.0f}"
    elif abs(value) >= 10:
        body = f"{value:,.1f}".rstrip("0").rstrip(".")
    else:
        body = f"{value:,.2f}".rstrip("0").rstrip(".")
    return f"{body}{unit}"


def render(spec: dict, output: Path) -> None:
    rows = list(spec.get("rows") or [])[:16]
    title = str(spec.get("title") or "SHEIN 经营图表")
    subtitle = str(spec.get("subtitle") or "")
    footnote = str(spec.get("footnote") or "")
    unit = str(spec.get("unit") or "")
    metric_label = str(spec.get("metricLabel") or "数值")

    width = int(spec.get("width") or 1400)
    row_h = 62
    top = 150 if subtitle else 120
    bottom = 108 if footnote else 78
    height = max(560, top + max(1, len(rows)) * row_h + bottom)

    bg = "#F7F8FA"
    card = "#FFFFFF"
    ink = "#111827"
    muted = "#6B7280"
    grid = "#E5E7EB"
    blue = "#2563EB"
    blue_soft = "#DBEAFE"
    orange = "#F97316"

    img = Image.new("RGB", (width, height), bg)
    draw = ImageDraw.Draw(img)

    font_title = load_font(42, bold=True)
    font_subtitle = load_font(24)
    font_label = load_font(24, bold=True)
    font_small = load_font(19)
    font_value = load_font(25, bold=True)
    font_axis = load_font(18)

    margin = 44
    draw.rounded_rectangle((24, 24, width - 24, height - 24), radius=32, fill=card)
    draw.text((margin, 42), ellipsize(draw, title, font_title, width - margin * 2), fill=ink, font=font_title)
    y = 96
    if subtitle:
        draw.text((margin, y), ellipsize(draw, subtitle, font_subtitle, width - margin * 2), fill=muted, font=font_subtitle)
        y += 36

    if not rows:
        draw.text((margin, y + 80), "当前数据不足，无法生成图表。", fill=muted, font=font_label)
        output.parent.mkdir(parents=True, exist_ok=True)
        img.save(output, "PNG", optimize=True)
        return

    values = []
    for r in rows:
        try:
            values.append(float(r.get("value") or 0))
        except Exception:
            values.append(0.0)
    max_value = max([0.0] + values)
    if max_value <= 0:
        max_value = 1.0

    label_x = margin
    label_w = 380
    bar_x = label_x + label_w + 24
    value_w = 220
    bar_w = width - bar_x - value_w - margin
    base_y = top

    draw.text((bar_x, base_y - 34), metric_label, fill=muted, font=font_axis)
    draw.line((bar_x, base_y - 8, bar_x + bar_w, base_y - 8), fill=grid, width=1)

    for idx, (row, value) in enumerate(zip(rows, values), start=1):
        y0 = base_y + (idx - 1) * row_h
        label = ellipsize(draw, str(row.get("label") or "-"), font_label, label_w - 42)
        note = ellipsize(draw, str(row.get("note") or ""), font_small, label_w - 8)
        rank = f"{idx:02d}"
        draw.text((label_x, y0 + 5), rank, fill=orange if idx <= 3 else muted, font=font_small)
        draw.text((label_x + 42, y0), label, fill=ink, font=font_label)
        if note:
            draw.text((label_x + 42, y0 + 31), note, fill=muted, font=font_small)

        track_y = y0 + 15
        draw.rounded_rectangle((bar_x, track_y, bar_x + bar_w, track_y + 24), radius=12, fill=blue_soft)
        fill_w = int(bar_w * max(0.0, value) / max_value)
        if fill_w > 0:
            draw.rounded_rectangle((bar_x, track_y, bar_x + fill_w, track_y + 24), radius=12, fill=blue)

        value_label = str(row.get("valueLabel") or fmt_number(value, unit))
        draw.text((bar_x + bar_w + 22, y0 + 8), value_label, fill=ink, font=font_value)

    # Simple axis hints.
    draw.text((bar_x, height - bottom + 16), "0", fill=muted, font=font_axis)
    max_label = fmt_number(max_value, unit)
    draw.text((bar_x + bar_w - text_width(draw, max_label, font_axis), height - bottom + 16), max_label, fill=muted, font=font_axis)
    draw.line((bar_x, height - bottom + 8, bar_x + bar_w, height - bottom + 8), fill=grid, width=1)

    if footnote:
        draw.text((margin, height - 64), ellipsize(draw, footnote, font_small, width - margin * 2), fill=muted, font=font_small)

    output.parent.mkdir(parents=True, exist_ok=True)
    img.save(output, "PNG", optimize=True)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True, help="Chart spec JSON path")
    parser.add_argument("--output", required=True, help="Output PNG path")
    args = parser.parse_args()
    spec = json.loads(Path(args.input).read_text(encoding="utf-8-sig"))
    render(spec, Path(args.output))


if __name__ == "__main__":
    main()
