#!/usr/bin/env node
import {spawnSync} from 'node:child_process';

const tests = [
  'scripts/marketing/smoke_coupon_budget_guard.mjs',
  'scripts/marketing/smoke_known_ordinary_price_guard.mjs',
  'scripts/marketing/smoke_limited_discount_drift_rescue_files.mjs',
  'scripts/marketing/smoke_limited_discount_drift_rescue_plan.mjs',
  'scripts/marketing/smoke_limited_repair_status.mjs',
  'scripts/marketing/smoke_marketing_repair_manifest.mjs',
  'scripts/marketing/smoke_marketing_repair_queue.mjs',
  'scripts/marketing/smoke_marketing_daily_group_report.mjs',
  'scripts/marketing/smoke_marketing_terminal_report_readiness.mjs',
  'scripts/marketing/smoke_bounded_fallback_resume.mjs',
  'scripts/marketing/smoke_high_click_special_policy.mjs',
  'scripts/marketing/smoke_shared_storage_cost.mjs',
  'scripts/marketing/smoke_marketing_cost_map_model.mjs',
  'scripts/marketing/smoke_ordinary_campaign_approval.mjs',
  'scripts/marketing/smoke_limited_discount_target_price_guard.mjs',
  'scripts/marketing/smoke_marketing_classifiers.mjs',
  'scripts/marketing/smoke_marketing_automation_authorization.mjs',
  'scripts/marketing/smoke_marketing_activity_inventory_transaction_policy.mjs',
  'scripts/marketing/smoke_marketing_activity_inventory_transaction.mjs',
  'scripts/marketing/smoke_marketing_activity_inventory_integration.mjs',
  'scripts/marketing/smoke_low_et_fast_seller_pricing.mjs',
  'scripts/marketing/smoke_low_et_fast_seller_integrations.mjs',
  'scripts/marketing/smoke_transactional_limited_discount_replacement.mjs',
  'scripts/marketing/smoke_marketing_pricing_policy.mjs',
  'scripts/marketing/smoke_authorized_fallback_inventory_top_up.mjs',
  'scripts/marketing/smoke_latest_raw_marketing_link_overlay.mjs',
  'scripts/marketing/smoke_current_marketing_live_scan_selection.mjs',
  'scripts/marketing/smoke_ordinary_activity_list_gap.mjs',
  'scripts/marketing/smoke_limited_discount_default_activity_stock.mjs',
  'scripts/marketing/smoke_manual_limited_discount_protection.mjs',
  'scripts/marketing/smoke_marketing_link_key_index.mjs',
  'scripts/marketing/smoke_merge_current_marketing_price_scans.mjs',
  'scripts/marketing/smoke_new_listing_limited_discount_plan_exact_price.mjs',
  'scripts/marketing/smoke_order_audit_linksdata_exact_target.mjs',
  'scripts/marketing/smoke_cloud_order_warehouse_fallback.mjs',
  'scripts/marketing/smoke_order_mitigation_history.mjs',
  'scripts/marketing/smoke_order_target_price_windows.mjs',
  'scripts/marketing/smoke_ordinary_composite_plan_tools.mjs',
  'scripts/marketing/smoke_ordinary_platform_price_policy.mjs',
  'scripts/marketing/smoke_ordinary_platform_tier_evidence.mjs',
  'scripts/marketing/smoke_platform_new_label_policy.mjs',
  'scripts/marketing/smoke_relisted_link_cost_fallback.mjs',
  'scripts/marketing/smoke_relisted_link_limited_discount_plan.mjs',
  'scripts/marketing/smoke_limited_discount_drift_activity_stock.mjs',
  'scripts/marketing/smoke_split_limited_discount_target_price_guard.mjs',
  'scripts/marketing/smoke_split_recreate_limited_discount_target_guard.mjs',
  'scripts/marketing/smoke_limited_discount_rescue_registry_source.mjs',
  'scripts/test_product_display_name.mjs',
  'scripts/test_product_match_key_schema.mjs',
  'scripts/test_product_sku_normalizer.mjs',
  'scripts/test_business_domain_fetch_contract.mjs',
  'scripts/test_marketing_plan_selector.mjs',
  'scripts/test_marketing_scan_resilience.mjs',
  'scripts/test_marketing_price_lead_merge.mjs',
  'scripts/test_cloud_watchdog_recovery.mjs',
  'scripts/test_cloud_watchdog_alert_state.mjs',
  'scripts/test_cloud_watchdog_issue_collapse.mjs',
  'scripts/test_cloud_data_coverage_policy.mjs',
  'scripts/test_cloud_manual_login_recovery.mjs',
  'scripts/test_session_manager_webapi_export_contract.mjs',
  'scripts/test_bi_client_resilience.mjs',
  'scripts/test_bi_frontend_accessibility.mjs',
  'scripts/test_bi_home_period_comparison.mjs',
  'scripts/test_bi_section_cache.mjs',
  'scripts/test_bi_portal_section_queue.mjs',
  'scripts/test_bi_portal_section_terminal.mjs',
  'scripts/test_bi_portal_data_mode.mjs',
  'scripts/test_bi_live_page_recovery.mjs',
  'scripts/test_bounded_top_level_json.mjs',
  'scripts/test_atomic_file_publish.mjs',
  'scripts/test_ops_run_bundle.mjs',
  'scripts/test_bi_profit_mart_freshness.mjs',
  'scripts/test_profit_refresh_pipeline_contract.mjs',
  'scripts/test_marketing_price_snapshot_health.mjs',
  'scripts/test_cloud_session_manager_reliability.mjs',
  'scripts/test_cloud_session_manager_latest_scope.mjs',
  'scripts/test_bi_ops_agent_governor.mjs',
  'scripts/test_bi_ops_model_policy.mjs',
  'scripts/test_bi_ops_intent_planner.mjs',
  'scripts/test_bi_ops_query_context.mjs',
  'scripts/test_bi_ops_direct_query.mjs',
  'scripts/test_bi_ops_query_retry.mjs',
  'scripts/test_owner_knowledge_policy.mjs',
  'scripts/test_owner_knowledge_service.mjs',
  'scripts/test_owner_knowledge_local_collector.mjs',
  'scripts/test_owner_knowledge_event_watch.mjs',
  'scripts/test_owner_knowledge_turn_ended.mjs',
  'scripts/test_owner_knowledge_distribution.mjs',
  'scripts/test_partner_knowledge_cache.mjs',
  'scripts/test_partner_cli_package.mjs',
  'scripts/test_partner_cli_updater.mjs',
  'scripts/test_partner_cli_portal_release.mjs',
  'scripts/test_partner_cli_release_pipeline.mjs',
  'scripts/test_link_ops_publish_asset_binding.mjs',
  'scripts/test_link_ops_product_descriptions.mjs',
  'scripts/test_link_ops_description_material_extract.mjs',
  'scripts/test_link_ops_extract_sk11004.mjs',
  'scripts/test_link_ops_prepare_descriptions_flow.mjs',
  'scripts/test_link_ops_update_description_flow.mjs',
  'scripts/test_link_ops_prepare_product_attribute_flow.mjs',
  'scripts/test_link_ops_executor_copy_batch_features.mjs',
  'scripts/test_link_ops_executor_live_source_titles.mjs',
  'scripts/test_link_ops_executor_source_detail_lock.mjs',
  'scripts/test_link_ops_image_role_planner.mjs',
  'scripts/test_link_retire_candidate_policy.mjs',
  'scripts/test_link_retire_candidates_from_csv.mjs',
  'scripts/test_retire_supplier_code_repair_payload.mjs',
  'scripts/test_shein_openapi_client_timeout.mjs',
  'scripts/test_openapi_stock_refresh_contract.mjs',
  'scripts/test_shein_webhook_receiver.mjs',
  'scripts/test_shein_webhook_audit_context.mjs',
  'scripts/test_shein_webhook_config.mjs',
  'scripts/test_shein_webhook_repository.mjs',
  'scripts/test_shein_webhook_write_gate.mjs',
  'scripts/test_shein_webhook_external_write_guard.mjs',
  'scripts/test_shein_webhook_handlers.mjs',
  'scripts/test_shein_webhook_product_state_migration.mjs',
  'scripts/test_shein_webhook_task_reconciler.mjs',
  'scripts/test_shein_webhook_order_return_sync.mjs',
  'scripts/test_shein_webhook_service.mjs',
  'scripts/test_notify_sync_issue.mjs',
  'scripts/test_lark_delivery_target.mjs',
  'scripts/test_shein_webhook_portal_contract.mjs',
  'scripts/test_webhook_primary_sales_migration.mjs',
  'scripts/test_bi_live_events_bridge.mjs',
  'scripts/test_bi_webhook_frontend.mjs',
  'scripts/test_link_ops_json_repository.mjs',
  'scripts/test_link_ops_store_gateway.mjs',
  'scripts/test_link_ops_job_worker.mjs',
  'scripts/test_link_ops_preflight_product_lock.mjs',
  'scripts/test_link_ops_product_model_identity_boundary.mjs',
  'scripts/test_link_ops_schema_sync.mjs',
  'scripts/test_link_ops_migration_compat.mjs',
  'scripts/test_migrate_link_ops_runtime_to_postgres.mjs',
  'scripts/test_morning_chain_reliability.mjs',
  'scripts/test_morning_chain_watchdog_stale_running.mjs',
  'scripts/test_morning_chain_wrapper_reliability.mjs',
  'scripts/test_shared_lock_security.mjs',
  'scripts/test_pipeline_marker.mjs',
  'scripts/test_morning_resume_evidence.mjs',
  'scripts/test_systemd_unit_snapshot.mjs',
  'scripts/test_cloud_runtime_snapshot.mjs',
  'scripts/test_cloud_disk_maintenance_contract.mjs',
  'scripts/test_host_resource_schedule_contract.mjs',
  'scripts/test_release_source_state.mjs',
  'scripts/test_systemd_security_contract.mjs',
  'scripts/test_bi_product_section_contract.mjs',
  'scripts/test_bi_product_profit_section_contract.mjs',
  'scripts/test_inventory_projection_contract.mjs',
  'scripts/test_inventory_replenishment_policy.mjs',
  'scripts/test_inventory_identity_alias_guard.mjs',
  'scripts/test_inventory_planner_alias_identity.mjs',
  'scripts/test_daily_inventory_replenishment_plan.mjs',
  'scripts/test_daily_inventory_current_detail_targeting.mjs',
  'scripts/test_daily_inventory_guard_targeted_detail.mjs',
  'scripts/test_et_low_inventory_safety_guard.mjs',
  'scripts/test_et_low_inventory_detail_evidence.mjs',
  'scripts/test_inventory_cost_ledger.mjs',
  'scripts/test_shein_openapi_readonly_retry.mjs',
  'scripts/test_shein_finance_check_orders.mjs',
  'scripts/test_storage_fee_bill_canonicalization.mjs',
  'scripts/test_et_storage_fee_sync_contract.mjs',
  'scripts/test_et_http_transport.mjs',
  'scripts/test_et_forwarder_runtime_contract.mjs',
  'scripts/test_read_transport_policy.mjs',
  'scripts/test_warehouse_business_logic_contract.mjs',
  'scripts/test_order_status_effective_evidence_contract.mjs',
  'scripts/smoke_browser_task_lease.mjs',
  'scripts/smoke_cloud_marketing_live_guard_resilience.mjs',
  'scripts/test_openapi_sales_loader_validity.mjs',
  'scripts/test_openapi_sales_mapping_contract.mjs',
  'scripts/test_historical_store_identity.mjs',
  'scripts/test_historical_store_identity_repair_contract.mjs',
  'scripts/test_openapi_product_reconciliation_policy.mjs',
  'scripts/test_openapi_product_detail_cache.mjs',
  'scripts/test_fetch_shein_openapi_products_stock_retry.mjs',
  'scripts/test_cloud_bi_refresh_lock_handoff.mjs',
  'scripts/test_portal_security.mjs',
  'scripts/test_portal_http_security.mjs',
  'scripts/test_owner_knowledge_portal_flow.mjs',
  'scripts/test_owner_knowledge_execute_distribution_guard.mjs',
  'scripts/test_owner_knowledge_execute_toctou_guard.mjs',
  'scripts/test_bi_ops_multitenant_isolation.mjs',
  'scripts/test_bi_ops_permissions.mjs',
  'scripts/test_bi_ops_chat_inference.mjs',
  'scripts/test_bi_ops_chat_action_matrix.mjs',
  'scripts/test_bi_ops_task_projection.mjs',
  'scripts/test_bi_ops_cli_flow.mjs',
  'scripts/test_bi_ops_intent_job_flow.mjs',
  'scripts/test_bi_ops_frontend_confirm_feedback.mjs',
  'scripts/test_shein_store_identity_merchant_fallback.mjs',
  'scripts/test_shein_browser_cdp.mjs',
  'scripts/test_local_browser_profile_cache_cleanup.mjs',
  'scripts/test_local_repo_hygiene_contract.mjs',
  'scripts/test_chrome_tmp_hygiene.mjs',
  'scripts/test_bi_ops_portal_shell_sync.mjs',
  'scripts/test_pending_discuss_batch.mjs',
  'scripts/test_pending_discuss_daily.mjs',
  'scripts/test_deterministic_timeout_contract.mjs',
];

const failures = [];
for (const file of tests) {
  const startedAt = Date.now();
  // Keep deterministic tests bounded and fail-fast, with explicit tiers only
  // where measured evidence exceeds the default. PR #99 CI attempt 1 killed
  // source-detail-lock at 30042ms on the default 30s tier; attempt 2 passed it
  // in 26012ms, then killed the attribute flow at 720017ms on its old 720s
  // tier, both by timeout SIGTERM with no assertion failure. Local evidence is
  // 24.7s for source-detail-lock and 709s for attribute flow. Their bounded
  // Attempt 3 then hit the description flow's former 240s bound at 240099ms
  // and the attribute flow's 900s bound at 900128ms. Their bounded 300s and
  // 1200s tiers keep measured CI headroom without disabling timeout. Update
  // descriptions keeps 240s, morning reliability keeps 120s, and every other
  // deterministic test keeps the default 30s budget.
  const timeout = file === 'scripts/test_link_ops_prepare_descriptions_flow.mjs'
    ? 300_000
    : file === 'scripts/test_link_ops_update_description_flow.mjs'
      ? 240_000
    : file === 'scripts/test_link_ops_executor_source_detail_lock.mjs'
      ? 60_000
      : file === 'scripts/test_link_ops_prepare_product_attribute_flow.mjs'
        ? 1_200_000
       : ['scripts/test_morning_chain_reliability.mjs',
         'scripts/test_morning_chain_wrapper_reliability.mjs',
         'scripts/test_cloud_session_manager_reliability.mjs'].includes(file)
         ? 120_000
       : 30_000;
  console.error(`START ${file} timeoutMs=${timeout}`);
  const result = spawnSync(process.execPath, [file], {
    cwd: process.cwd(),
    encoding: 'utf8',
    timeout,
    maxBuffer: 32 * 1024 * 1024,
  });
  const durationMs = Date.now() - startedAt;
  if (result.status !== 0) {
    failures.push({file, status: result.status, signal: result.signal, durationMs, stdout: result.stdout, stderr: result.stderr});
    console.error(`FAIL ${file} (${durationMs}ms)`);
  } else {
    console.log(`PASS ${file} (${durationMs}ms)`);
  }
}

if (failures.length) {
  console.error(JSON.stringify({ok: false, passed: tests.length - failures.length, failed: failures}, null, 2));
  process.exit(1);
}

console.log(JSON.stringify({ok: true, passed: tests.length, failed: 0}, null, 2));
