#!/usr/bin/env node
/**
 * Deprecated: sync normalized SHEIN link-management JSON into Lark Base.
 *
 * Input files are generated by scripts/fetch_shein_links.mjs.
 * This script creates/maintains dedicated link-management tables and writes
 * records idempotently by the "唯一键" field.
 *
 * The Feishu/Lark link-management feature has been retired. Production link
 * data now flows to local JSON/PostgreSQL/BI only. Keep this file for
 * emergency historical migration, but refuse to write unless explicitly
 * enabled with SHEIN_ENABLE_DEPRECATED_LARK_LINK_SYNC=1.
 */
import fsSync from 'node:fs';
import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {spawn} from 'node:child_process';

if (process.env.SHEIN_ENABLE_DEPRECATED_LARK_LINK_SYNC !== '1') {
  console.error([
    'Deprecated Feishu/Lark link-management sync is disabled.',
    'Use scripts/run_link_management_job.mjs without --lark for the supported BI/local flow.',
    'Set SHEIN_ENABLE_DEPRECATED_LARK_LINK_SYNC=1 only for an explicit one-off historical migration.'
  ].join('\n'));
  process.exit(2);
}

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const STATE_PATH = path.join(ROOT, 'state', 'lark_base.json');
const STORES_PATH = path.join(ROOT, 'config', 'stores.json');
const LINK_DIR = path.join(ROOT, 'outputs', 'shein_links');
const PAYLOAD_DIR = path.join(ROOT, 'outputs', 'lark_payloads');

const TABLES = {
  linkMain: '链接管理-链接主数据',
  performance: '链接管理-表现日事实',
  inventory: '链接管理-展示库存日事实',
  coverage: '链接管理-货号店铺覆盖',
  suggestion: '链接管理-建议',
  actionList: '链接管理-今日实操清单',
};
const DASHBOARD_NAME = 'SHEIN链接管理看板 v2';

function parseArgs(argv) {
  const args = {
    group: 'DSY',
    stores: null,
    date: null,
    files: [],
    ensureOnly: false,
    viewsOnly: false,
    syncDashboard: false,
    setupDashboard: false,
    cleanDashboard: false,
    skipLinkMainUpdates: false,
    maxActionsPerStore: 8,
    actionsOnly: false,
    suggestionsOnly: false,
    hideStaleActions: false,
  };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a === '--date') args.date = argv[++i];
    else if (a === '--group') args.group = argv[++i].toUpperCase();
    else if (a === '--stores') args.stores = argv[++i].split(',').map(s => s.trim().toUpperCase()).filter(Boolean);
    else if (a === '--store') args.stores = [argv[++i].trim().toUpperCase()];
    else if (a === '--file') args.files.push(path.resolve(argv[++i]));
    else if (a === '--ensure-only') args.ensureOnly = true;
    else if (a === '--views-only') args.viewsOnly = true;
    else if (a === '--no-dashboard-data') args.syncDashboard = false;
    else if (a === '--dashboard') args.setupDashboard = true;
    else if (a === '--no-dashboard') args.setupDashboard = false;
    else if (a === '--clean-dashboard') args.cleanDashboard = true;
    else if (a === '--skip-link-main-updates') args.skipLinkMainUpdates = true;
    else if (a === '--max-actions-per-store') args.maxActionsPerStore = Math.max(0, Number(argv[++i] || 8));
    else if (a === '--actions-only') args.actionsOnly = true;
    else if (a === '--suggestions-only') args.suggestionsOnly = true;
    else if (a === '--hide-stale-actions') args.hideStaleActions = true;
  }
  if (!args.date && !args.files.length && !args.ensureOnly && !args.viewsOnly) throw new Error('Use --date, --file, --ensure-only, or --views-only');
  if (args.viewsOnly && !args.date) throw new Error('Use --date with --views-only');
  return args;
}

function textField(name, extra = {}) { return {type: 'text', name, ...extra}; }
function numField(name, precision = 0) {
  return {type: 'number', name, style: {type: 'plain', precision, percentage: false, thousands_separator: true}};
}
function boolField(name) { return {type: 'checkbox', name}; }
function dateField(name) { return {type: 'datetime', name, style: {format: 'yyyy-MM-dd'}}; }
function dateTimeField(name) { return {type: 'datetime', name, style: {format: 'yyyy-MM-dd HH:mm'}}; }

const SCHEMA = {
  [TABLES.linkMain]: [
    textField('唯一键'), dateField('日期'), textField('分组'), textField('店铺代号'), textField('店铺名称'),
    textField('标准货号'), textField('原始货号'), textField('清洗后货号'), textField('前缀备注'),
    boolField('是否需货号复核'), textField('货号复核原因'),
    textField('SPU'), textField('SPU Code'), textField('SKC'), textField('SKC Code'), textField('SKU Code'),
    numField('SKU数量'), textField('销售属性'), textField('商品标题'), textField('商品图片', {style: {type: 'url'}}),
    textField('品牌'), textField('类目ID'), textField('链接状态'), boolField('是否已上架'), boolField('是否待上架'),
    boolField('是否已售罄'), boolField('是否已下架'), boolField('是否硬死链'), boolField('是否活动中'),
    boolField('是否待上架阻塞'), boolField('是否缺证书/资料'), textField('待上架阻塞类型'), textField('待上架阻塞原因'),
    textField('上架要求码'), textField('上架方式码'),
    boolField('是否废弃标记'), textField('创建时间'), textField('发布时间'), textField('首次上架时间'),
    textField('预计上架时间'), textField('商品标签'), textField('SKC标签'), textField('原始摘要'),
    dateTimeField('最近抓取时间'),
  ],
  [TABLES.performance]: [
    textField('唯一键'), dateField('日期'), textField('分组'), textField('店铺代号'), textField('店铺名称'),
    textField('标准货号'), textField('原始货号'), textField('SPU'), textField('SKC'), textField('商品名称'),
    textField('商品图片', {style: {type: 'url'}}), textField('新品标签'), textField('商品层级'),
    textField('在售标记'), textField('销售标记'), textField('活动标签'), textField('活动名称'),
    numField('当日销量'), numField('当日支付订单数'), numField('当日曝光人数'), numField('当日商详访客'),
    numField('当日点击率', 4), numField('当日加车访客'), numField('当日加车次数'), numField('当日加车率', 4),
    numField('当日支付人数'), numField('当日支付率', 4),
    numField('近7天销量'), numField('前7天销量'), numField('近30天销量'), numField('近7天支付订单数'),
    numField('近7天曝光人数'), numField('前7天曝光人数'), numField('近7天商详访客'),
    numField('近7天点击率', 4), numField('近7天支付率', 4), numField('近30天曝光人数'),
    numField('近30天商详访客'), numField('近30天点击率', 4), numField('近30天支付率', 4),
    numField('近7天销量环比', 4), numField('近7天曝光环比', 4),
    textField('质量等级'), numField('评论数'), numField('差评率', 4), numField('支付口径评论数'),
    numField('支付口径差评率', 4), numField('退货单数'), numField('退货件数'),
    textField('一级类目'), textField('二级类目'), textField('三级类目'), textField('四级类目'),
    textField('榜单名称'), textField('榜单类型'), numField('榜单排名'),
    textField('官方诊断标签'), textField('官方建议'), textField('官方操作按钮'), textField('原始摘要'),
    dateTimeField('最近抓取时间'),
  ],
  [TABLES.inventory]: [
    textField('唯一键'), dateField('日期'), textField('分组'), textField('店铺代号'), textField('店铺名称'),
    textField('标准货号'), textField('原始货号'), textField('SPU'), textField('SKC'), textField('SKU Code'),
    textField('SKU属性'), textField('商品图片', {style: {type: 'url'}}), textField('类目'),
    textField('上架日期'), numField('上架天数'), textField('供货状态'), textField('上架状态'),
    textField('销售模式'), textField('质量等级'), textField('商品层级'), textField('库存预警状态'),
    textField('运营标签'), textField('权益标签'), textField('商品标签'),
    numField('平台展示库存'), numField('平台可售库存'), numField('待发货数量'), numField('待上架数量'),
    numField('在途数量'), numField('商家仓库存'), numField('近7天销量'), numField('近30天销量'),
    numField('累计销量'), numField('订单数量'), numField('建议下单数'), numField('可下单数'),
    numField('系统下单数'), numField('商家下单数'), numField('最小平台可售天数'), numField('最大平台可售天数'),
    textField('价格区间'), textField('最终价区间'), textField('采购价区间'),
    boolField('展示库存偏低'), textField('展示库存预警原因'), textField('真实库存状态'),
    textField('原始摘要'), dateTimeField('最近抓取时间'),
  ],
  [TABLES.coverage]: [
    textField('唯一键'), dateField('日期'), textField('分组'), textField('店铺代号'), textField('店铺名称'),
    textField('标准货号'), textField('覆盖状态'), boolField('是否有上架链接'), boolField('是否需要补链接'), boolField('全店均无上架暂不提醒'),
    numField('链接总数'), numField('已上架链接数'), numField('待上架链接数'), numField('已售罄链接数'),
    numField('已下架链接数'), numField('硬死链数'), boolField('是否多条上架链接'),
    textField('最佳SKC'), numField('最佳链接近30天销量'), textField('SKC列表'), textField('建议动作'),
    textField('原始摘要'), dateTimeField('最近抓取时间'),
  ],
  [TABLES.suggestion]: [
    textField('唯一键'), dateField('日期'), textField('分组'), textField('店铺代号'), textField('店铺名称'),
    textField('目标类型'), textField('目标键'), textField('标准货号'), textField('SKC'),
    textField('规则代码'), textField('建议类型'), textField('优先级'), textField('原因'), textField('建议动作'),
    textField('证据'), textField('处理状态'), dateTimeField('最近抓取时间'),
  ],
  [TABLES.actionList]: [
    textField('唯一键'), dateField('日期'), numField('今日排序'), textField('处理状态'), boolField('是否纳入今日清单'), boolField('是否今日重点'),
    textField('实操规则版本'),
    textField('优先级'), textField('操作分类'), textField('一句话动作'), textField('店铺代号'), textField('分组'), textField('店铺名称'),
    textField('SKC'), textField('标准货号'), textField('目标类型'), textField('目标键'), textField('原始建议类型'), textField('规则代码'),
    textField('为什么'), textField('证据'), textField('建议动作'), dateTimeField('最近抓取时间'),
  ]
};

function parseFirstJson(stdout) {
  const text = String(stdout || '').trim();
  const starts = [text.indexOf('{'), text.indexOf('[')].filter(i => i >= 0);
  const start = starts.length ? Math.min(...starts) : -1;
  if (start < 0) throw new Error(`No JSON in lark-cli output: ${text.slice(0, 500)}`);
  return JSON.parse(text.slice(start));
}
async function writePayload(name, obj) {
  await fs.mkdir(PAYLOAD_DIR, {recursive: true});
  const safe = name.replace(/[^a-z0-9._-]+/gi, '-');
  const file = path.join(PAYLOAD_DIR, `${Date.now()}-${safe}.json`);
  await fs.writeFile(file, JSON.stringify(obj, null, 2), 'utf8');
  return file;
}
async function runLarkOnce(args, payloadName = null, payload = null) {
  const finalArgs = [...args];
  if (payload !== null && payload !== undefined) {
    const payloadFile = await writePayload(payloadName || 'payload', payload);
    finalArgs.push('--json', `@${path.relative(ROOT, payloadFile).replace(/\\/g, '/')}`);
  }
  return await new Promise((resolve, reject) => {
    const child = spawn('lark-cli', finalArgs, {cwd: ROOT, stdio: ['ignore', 'pipe', 'pipe']});
    let stdout = '';
    let stderr = '';
    child.stdout.setEncoding('utf8');
    child.stderr.setEncoding('utf8');
    child.stdout.on('data', d => stdout += d);
    child.stderr.on('data', d => stderr += d);
    child.on('close', code => {
      let parsed = null;
      try { parsed = parseFirstJson(stdout || stderr); } catch {}
      if (code !== 0 && (String(parsed?.error?.code || '') === '800070003' || /800070003|no operation produced/i.test(`${stdout}\n${stderr}`))) {
        resolve({stdout, stderr, parsed: {...parsed, noop: true}});
      } else if (code !== 0) reject(new Error(parsed?.error?.message || stderr || stdout || `lark-cli exited ${code}`));
      else resolve({stdout, stderr, parsed});
    });
    child.on('error', reject);
  });
}
async function runLark(args, payloadName = null, payload = null, attempts = 5) {
  let lastError = null;
  for (let attempt = 1; attempt <= attempts; attempt++) {
    try { return await runLarkOnce(args, payloadName, payload); }
    catch (err) {
      lastError = err;
      const msg = String(err?.message || err);
      const rateLimited = /limited|rate.?limit|800004135|OpenAPISearchRecord limited/i.test(msg);
      const retryable = rateLimited || /EOF|ECONNRESET|ETIMEDOUT|timeout|503|502|504|5000|HTTP 500|tls|x509|certificate|not open\.feishu\.cn/i.test(msg);
      if (!retryable || attempt === attempts) break;
      await new Promise(r => setTimeout(r, rateLimited ? attempt * 10_000 : attempt * 2500));
    }
  }
  throw lastError;
}

async function readJson(file) {
  return JSON.parse((await fs.readFile(file, 'utf8')).replace(/^\uFEFF/, ''));
}
async function fileExists(file) {
  try {
    await fs.access(file);
    return true;
  } catch {
    return false;
  }
}
async function saveState(state) {
  await fs.writeFile(STATE_PATH, JSON.stringify(state, null, 2), 'utf8');
}
function getTableIdFromCreate(resp) {
  return resp.parsed?.data?.table?.id || resp.parsed?.data?.table?.table_id || resp.parsed?.table?.id || resp.parsed?.table?.table_id;
}
async function listTables(baseToken) {
  const resp = await runLark(['base', '+table-list', '--as', 'user', '--base-token', baseToken, '--offset', '0', '--limit', '100']);
  return resp.parsed?.data?.items || resp.parsed?.data?.tables || resp.parsed?.items || [];
}
async function listFields(baseToken, tableId) {
  const resp = await runLark(['base', '+field-list', '--as', 'user', '--base-token', baseToken, '--table-id', tableId, '--offset', '0', '--limit', '200']);
  return resp.parsed?.data?.items || resp.parsed?.data?.fields || resp.parsed?.items || [];
}
async function listViews(baseToken, tableId) {
  const resp = await runLark(['base', '+view-list', '--as', 'user', '--base-token', baseToken, '--table-id', tableId, '--offset', '0', '--limit', '100']);
  return resp.parsed?.data?.views || resp.parsed?.data?.items || resp.parsed?.views || resp.parsed?.items || [];
}
async function createView(baseToken, tableId, name, type = 'grid') {
  const resp = await runLark(['base', '+view-create', '--as', 'user', '--base-token', baseToken, '--table-id', tableId], `view-${name}`, {name, type});
  return resp.parsed?.data?.view || resp.parsed?.data?.item || resp.parsed?.view || resp.parsed?.item || resp.parsed;
}
function resolveViewId(view) {
  return view?.view_id || view?.id || view?.viewId || view?.data?.view?.view_id || view?.data?.view?.id || view?.data?.id;
}
async function ensureTable(baseToken, state, tableName, fields) {
  const existingTables = await listTables(baseToken);
  const existing = existingTables.find(t => t.name === tableName);
  let tableId = existing?.table_id || existing?.id || state.tables?.[tableName]?.table_id;
  if (!tableId) {
    const resp = await runLark([
      'base', '+table-create', '--as', 'user', '--base-token', baseToken,
      '--name', tableName, '--fields', JSON.stringify(fields),
    ], null, null, 5);
    tableId = getTableIdFromCreate(resp);
    if (!tableId) throw new Error(`Cannot get table id for created table ${tableName}`);
    console.log(`[base] created table ${tableName} ${tableId}`);
  } else {
    console.log(`[base] table exists ${tableName} ${tableId}`);
    const existingFields = await listFields(baseToken, tableId);
    const names = new Set(existingFields.map(f => f.name));
    for (const field of fields) {
      if (names.has(field.name)) continue;
      await runLark(['base', '+field-create', '--as', 'user', '--base-token', baseToken, '--table-id', tableId], `field-${tableName}-${field.name}`, field);
      console.log(`[base] added field ${tableName}.${field.name}`);
      await new Promise(r => setTimeout(r, 700));
    }
  }
  state.tables ||= {};
  state.tables[tableName] = {
    ...(state.tables[tableName] || {}),
    table_id: tableId,
    managed_by: 'scripts/sync_shein_links_to_lark.mjs',
    updated_at: new Date().toISOString(),
  };
  return tableId;
}
async function ensureAllTables(baseToken, state) {
  const ids = {};
  for (const [name, fields] of Object.entries(SCHEMA)) {
    ids[name] = await ensureTable(baseToken, state, name, fields);
    await saveState(state);
  }
  return ids;
}

async function listRecordEntries(baseToken, tableId) {
  const entries = [];
  let offset = 0;
  while (true) {
    const resp = await runLark([
      'base', '+record-list', '--as', 'user', '--base-token', baseToken, '--table-id', tableId,
      '--field-id', '唯一键', '--offset', String(offset), '--limit', '200', '--format', 'json',
    ]);
    const data = resp.parsed?.data || {};
    const rows = data.data || [];
    const ids = data.record_id_list || [];
    const fields = data.fields || [];
    const keyIndex = Math.max(0, fields.indexOf('唯一键'));
    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];
      const key = Array.isArray(row) ? row[keyIndex] : (row?.fields?.['唯一键'] ?? row?.['唯一键']);
      const recordId = ids[i] || row?.record_id || row?.id || null;
      if (key && recordId) entries.push({uniqueKey: String(key), recordId});
    }
    if (!data.has_more) break;
    offset += rows.length || 200;
  }
  return entries;
}
async function listRecordMap(baseToken, tableId) {
  const map = new Map();
  for (const {uniqueKey, recordId} of await listRecordEntries(baseToken, tableId)) {
    if (!map.has(uniqueKey)) map.set(uniqueKey, recordId);
  }
  return map;
}
function cleanRecord(record) {
  const out = {};
  for (const [k, v] of Object.entries(record)) {
    if (v === undefined || Number.isNaN(v)) out[k] = null;
    else out[k] = v;
  }
  return out;
}
async function batchCreate(baseToken, tableId, records, label) {
  const results = [];
  for (let i = 0; i < records.length; i += 200) {
    const chunk = records.slice(i, i + 200);
    if (!chunk.length) continue;
    const fields = Object.keys(chunk[0]);
    const payload = {fields, rows: chunk.map(r => fields.map(f => r[f] ?? null))};
    const resp = await runLark(['base', '+record-batch-create', '--as', 'user', '--base-token', baseToken, '--table-id', tableId], `${label}-create-${i}`, payload);
    const ids = resp.parsed?.data?.record_id_list || [];
    chunk.forEach((r, idx) => results.push({uniqueKey: r['唯一键'], action: 'created', recordId: ids[idx] || null}));
    await new Promise(r => setTimeout(r, 700));
  }
  return results;
}
async function updateOne(baseToken, tableId, recordId, record, label) {
  await runLark(['base', '+record-upsert', '--as', 'user', '--base-token', baseToken, '--table-id', tableId, '--record-id', recordId], `${label}-update-${record['唯一键']}`, record);
  await new Promise(r => setTimeout(r, 350));
  return {uniqueKey: record['唯一键'], action: 'updated', recordId};
}
async function deleteOne(baseToken, tableId, recordId, uniqueKey, label) {
  await runLark(['base', '+record-delete', '--as', 'user', '--base-token', baseToken, '--table-id', tableId, '--record-id', recordId, '--yes']);
  await new Promise(r => setTimeout(r, 350));
  return {uniqueKey, action: 'deleted', recordId, label};
}
async function upsertRecords(baseToken, tableId, records, label, options = {}) {
  const byKey = new Map();
  for (const record of records.map(cleanRecord).filter(r => r['唯一键'])) {
    byKey.set(String(record['唯一键']), record);
  }
  const clean = [...byKey.values()];
  if (!clean.length && !options.deleteStalePrefixes?.length) return [];
  const entries = await listRecordEntries(baseToken, tableId);
  const existing = new Map();
  const duplicates = [];
  for (const entry of entries) {
    if (!existing.has(entry.uniqueKey)) existing.set(entry.uniqueKey, entry.recordId);
    else duplicates.push(entry);
  }
  const creates = [];
  const updates = [];
  for (const record of clean) {
    const id = existing.get(String(record['唯一键']));
    if (id && options.skipUpdates) continue;
    if (id) updates.push({recordId: id, record});
    else creates.push(record);
  }
  const results = [];
  results.push(...await batchCreate(baseToken, tableId, creates, label));
  for (const item of updates) results.push(await updateOne(baseToken, tableId, item.recordId, item.record, label));
  let duplicateDeleted = 0;
  const deletedRecordIds = new Set();
  for (const {uniqueKey, recordId} of duplicates) {
    results.push(await deleteOne(baseToken, tableId, recordId, uniqueKey, `${label}-duplicate`));
    deletedRecordIds.add(recordId);
    duplicateDeleted += 1;
  }
  let deleted = 0;
  if (options.deleteStalePrefixes?.length) {
    const currentKeys = new Set(clean.map(r => String(r['唯一键'])));
    for (const {uniqueKey: key, recordId} of entries) {
      if (deletedRecordIds.has(recordId)) continue;
      if (currentKeys.has(key)) continue;
      if (!options.deleteStalePrefixes.some(prefix => key.startsWith(prefix))) continue;
      results.push(await deleteOne(baseToken, tableId, recordId, key, label));
      deletedRecordIds.add(recordId);
      deleted += 1;
    }
  }
  console.log(`[sync] ${label}: create=${creates.length}, update=${updates.length}, skipped=${options.skipUpdates ? clean.length - creates.length - updates.length : 0}, duplicateDelete=${duplicateDeleted}, delete=${deleted}`);
  return results;
}

function storeConfig() {
  return JSON.parse(fsSyncRead(STORES_PATH));
}
function fsSyncRead(file) {
  return globalThis.__syncFsRead
    ? globalThis.__syncFsRead(file)
    : fsSync.readFileSync(file, 'utf8');
}

function dateTime(fetchTime) { return String(fetchTime || '').slice(0, 16); }
function linkRecord(row, fetchTime) {
  return {
    '唯一键': row.uniqueKey,
    '日期': row.date,
    '分组': row.groupKey,
    '店铺代号': row.storeKey,
    '店铺名称': row.shopName,
    '标准货号': row.standardGoodsSn,
    '原始货号': row.rawGoodsSn,
    '清洗后货号': row.cleanedGoodsSn,
    '前缀备注': row.leadingAnnotation,
    '是否需货号复核': row.needsGoodsSnReview,
    '货号复核原因': row.goodsSnReviewReason,
    'SPU': row.spu,
    'SPU Code': row.spuCode,
    'SKC': row.skc,
    'SKC Code': row.skcCode,
    'SKU Code': row.skuCodes,
    'SKU数量': row.skuCount,
    '销售属性': row.saleName,
    '商品标题': row.productNameCn || row.productNameEn || row.productNameMulti,
    '商品图片': row.imageUrl,
    '品牌': row.brandName,
    '类目ID': String(row.categoryId || ''),
    '链接状态': row.shelfStatusName,
    '是否已上架': row.isOnShelf,
    '是否待上架': row.isWaitShelf,
    '是否已售罄': row.isSoldOut,
    '是否已下架': row.isOutShelf,
    '是否硬死链': row.isHardDead,
    '是否待上架阻塞': row.waitShelfBlocked,
    '是否缺证书/资料': row.waitShelfRequiresCertificate,
    '待上架阻塞类型': row.waitShelfBlockType,
    '待上架阻塞原因': row.waitShelfBlockReason,
    '上架要求码': row.shelfRequireList,
    '上架方式码': row.shelfWayList,
    '是否活动中': row.hasActivity,
    '是否废弃标记': row.abandoned,
    '创建时间': row.createTime,
    '发布时间': row.publishTime,
    '首次上架时间': row.firstShelfTime,
    '预计上架时间': row.expectShelfTime,
    '商品标签': row.productTags,
    'SKC标签': row.skcTags,
    '原始摘要': row.rawSummary,
    '最近抓取时间': dateTime(fetchTime),
  };
}
function performanceRecord(row, fetchTime) {
  return {
    '唯一键': row.uniqueKey, '日期': row.date, '分组': row.groupKey, '店铺代号': row.storeKey, '店铺名称': row.shopName,
    '标准货号': row.standardGoodsSn, '原始货号': row.rawGoodsSn, 'SPU': row.spu, 'SKC': row.skc,
    '商品名称': row.goodsName, '商品图片': row.imageUrl, '新品标签': row.newGoodsTag, '商品层级': row.layerName,
    '在售标记': row.onSaleFlag, '销售标记': row.saleFlag, '活动标签': row.activityTag, '活动名称': row.activityNames,
    '当日销量': row.saleCnt, '当日支付订单数': row.payOrderCnt, '当日曝光人数': row.epsUv, '当日商详访客': row.goodsUv,
    '当日点击率': row.clickRate, '当日加车访客': row.cartUv, '当日加车次数': row.cartPv, '当日加车率': row.cartRate,
    '当日支付人数': row.payUv, '当日支付率': row.payRate,
    '近7天销量': row.c7SaleCnt, '前7天销量': row.prev7SaleCnt, '近30天销量': row.c30SaleCnt, '近7天支付订单数': row.c7PayOrderCnt,
    '近7天曝光人数': row.c7EpsUv, '前7天曝光人数': row.prev7EpsUv, '近7天商详访客': row.c7GoodsUv,
    '近7天点击率': row.c7ClickRate, '近7天支付率': row.c7PayRate, '近30天曝光人数': row.c30EpsUv,
    '近30天商详访客': row.c30GoodsUv, '近30天点击率': row.c30ClickRate, '近30天支付率': row.c30PayRate,
    '近7天销量环比': row.sale7ChangeRate, '近7天曝光环比': row.exposure7ChangeRate,
    '质量等级': row.totalQualityLevel, '评论数': row.totalCommentCnt, '差评率': row.badCommentRate,
    '支付口径评论数': row.payCommentCnt, '支付口径差评率': row.payBadCommentRate, '退货单数': row.returnOrderCnt, '退货件数': row.returnQty,
    '一级类目': row.category1, '二级类目': row.category2, '三级类目': row.category3, '四级类目': row.category4,
    '榜单名称': row.listName, '榜单类型': row.listType, '榜单排名': row.listRank,
    '官方诊断标签': row.flowDiagnoseTabs, '官方建议': row.officialSuggestion, '官方操作按钮': row.officialOperateButtons,
    '原始摘要': row.rawSummary, '最近抓取时间': dateTime(fetchTime),
  };
}
function inventoryRecord(row, fetchTime) {
  const sourceWarnWasLow = Boolean(row.displayStockLow);
  return {
    '唯一键': row.uniqueKey, '日期': row.date, '分组': row.groupKey, '店铺代号': row.storeKey, '店铺名称': row.shopName,
    '标准货号': row.standardGoodsSn, '原始货号': row.rawGoodsSn, 'SPU': row.spu, 'SKC': row.skc,
    'SKU Code': row.skuCodes, 'SKU属性': row.skuAttrs, '商品图片': row.imageUrl, '类目': row.categoryName,
    '上架日期': row.shelfDate, '上架天数': row.shelfDays, '供货状态': row.supplyStatus, '上架状态': row.shelfStatus,
    '销售模式': row.saleModel, '质量等级': row.qualityGrade, '商品层级': row.goodsLevel, '库存预警状态': row.stockWarnStatus,
    '运营标签': row.operateLabels, '权益标签': row.rightsLabels, '商品标签': row.goodsLabels,
    '平台展示库存': row.platformDisplayStock, '平台可售库存': row.platformSaleableStock,
    '待发货数量': row.stayDeliver, '待上架数量': row.stayShelf, '在途数量': row.transit, '商家仓库存': row.supplierStock,
    '近7天销量': row.c7dSaleCnt, '近30天销量': row.c30dSaleCnt, '累计销量': row.totalSaleVolume, '订单数量': row.orderCnt,
    '建议下单数': row.adviceOrderCount, '可下单数': row.availableOrderCount, '系统下单数': row.systemOrderCount, '商家下单数': row.userOrderCount,
    '最小平台可售天数': row.minStockSaleDays, '最大平台可售天数': row.maxStockSaleDays,
    '价格区间': row.priceRange, '最终价区间': row.finalPriceRange, '采购价区间': row.purchasePriceRange,
    '展示库存偏低': false,
    '展示库存预警原因': sourceWarnWasLow ? '备货信息库存口径不可靠，已暂停用它触发展示库存预警' : row.displayStockWarningReason,
    '真实库存状态': row.realInventoryStatus,
    '原始摘要': row.rawSummary, '最近抓取时间': dateTime(fetchTime),
  };
}
function coverageRecord(row, fetchTime) {
  return {
    '唯一键': row.uniqueKey, '日期': row.date, '分组': row.groupKey, '店铺代号': row.storeKey, '店铺名称': row.shopName,
    '标准货号': row.standardGoodsSn, '覆盖状态': row.coverageStatus, '是否有上架链接': row.hasOnShelfLink, '是否需要补链接': row.needSupplementLink,
    '全店均无上架暂不提醒': row.allStoresNoOnShelfNoReminder,
    '链接总数': row.linkCount, '已上架链接数': row.onShelfCount, '待上架链接数': row.waitShelfCount,
    '已售罄链接数': row.soldOutCount, '已下架链接数': row.outShelfCount, '硬死链数': row.hardDeadCount,
    '是否多条上架链接': row.duplicateOnShelf, '最佳SKC': row.bestSkc, '最佳链接近30天销量': row.bestLinkC30Sale,
    'SKC列表': row.skcList, '建议动作': row.recommendation, '原始摘要': row.rawSummary, '最近抓取时间': dateTime(fetchTime),
  };
}
function suggestionRecord(row, fetchTime) {
  return {
    '唯一键': row.uniqueKey, '日期': row.date, '分组': row.groupKey, '店铺代号': row.storeKey, '店铺名称': row.shopName,
    '目标类型': row.targetType, '目标键': row.targetKey, '标准货号': row.standardGoodsSn, 'SKC': row.skc,
    '规则代码': row.ruleCode, '建议类型': row.suggestionType, '优先级': row.priority,
    '原因': row.reason, '建议动作': row.action, '证据': row.evidence, '处理状态': '待处理', '最近抓取时间': dateTime(fetchTime),
  };
}

function metric(value, fallback = 0) {
  const n = Number(value);
  return Number.isFinite(n) ? n : fallback;
}

function indexKey(storeKey, id) {
  return `${storeKey || ''}__${id || ''}`;
}

function buildActionContext(objects, suppressedStandards = new Set()) {
  const perfByStoreSkc = new Map();
  const invByStoreSkc = new Map();
  const covByStoreSku = new Map();
  const standardStats = new Map();
  const getStats = standardGoodsSn => {
    const key = standardGoodsSn || '';
    if (!standardStats.has(key)) {
      standardStats.set(key, {
        stores: new Set(),
        onShelfStores: new Set(),
        onShelfCount: 0,
        c7SaleCnt: 0,
        c30SaleCnt: 0,
        c30EpsUv: 0,
      });
    }
    return standardStats.get(key);
  };
  for (const {obj} of objects) {
    const storeKey = obj.store?.storeKey || '';
    for (const row of obj.coverageRows || []) {
      covByStoreSku.set(indexKey(row.storeKey || storeKey, row.standardGoodsSn), row);
      if (!row.standardGoodsSn) continue;
      const stats = getStats(row.standardGoodsSn);
      stats.stores.add(row.storeKey || storeKey);
      if (row.hasOnShelfLink) stats.onShelfStores.add(row.storeKey || storeKey);
      stats.onShelfCount += metric(row.onShelfCount, 0);
    }
    for (const row of obj.performanceRows || []) {
      perfByStoreSkc.set(indexKey(row.storeKey || storeKey, row.skc), row);
      if (!row.standardGoodsSn) continue;
      const stats = getStats(row.standardGoodsSn);
      stats.c7SaleCnt += metric(row.c7SaleCnt, 0);
      stats.c30SaleCnt += metric(row.c30SaleCnt, 0);
      stats.c30EpsUv += metric(row.c30EpsUv, 0);
    }
    for (const row of obj.inventoryRows || []) {
      invByStoreSkc.set(indexKey(row.storeKey || storeKey, row.skc), row);
    }
  }
  return {perfByStoreSkc, invByStoreSkc, covByStoreSku, standardStats, suppressedStandards};
}

function actionPerf(row, ctx) {
  return ctx.perfByStoreSkc.get(indexKey(row.storeKey, row.skc)) || {};
}

function actionInventory(row, ctx) {
  return ctx.invByStoreSkc.get(indexKey(row.storeKey, row.skc)) || {};
}

function actionCoverage(row, ctx) {
  return ctx.covByStoreSku.get(indexKey(row.storeKey, row.standardGoodsSn)) || {};
}

function actionStandardStats(row, ctx) {
  return ctx.standardStats.get(row.standardGoodsSn || '') || {
    stores: new Set(),
    onShelfStores: new Set(),
    onShelfCount: 0,
    c7SaleCnt: 0,
    c30SaleCnt: 0,
    c30EpsUv: 0,
  };
}

function normalizeSuggestionRows(objects, suppressedStandards = new Set()) {
  for (const {obj} of objects) {
    obj.suggestionRows = (obj.suggestionRows || [])
      .filter(row => !['HARD_DEAD_LINK', 'DISPLAY_STOCK_LOW'].includes(row.ruleCode) && !suppressedStandards.has(row.standardGoodsSn))
      .map(row => ({
        ...row,
        allStoresNoOnShelfNoReminder: suppressedStandards.has(row.standardGoodsSn),
      }));
  }
}

function actionCategory(row) {
  const code = row.ruleCode || '';
  if (code === 'COVERAGE_MISSING') return '补上架链接';
  if (code === 'WAIT_SHELF_BLOCKED') return row.suggestionType?.includes('证书') ? '补证书/资料' : '处理待上架卡点';
  if (code === 'DISPLAY_STOCK_LOW') return '调高展示库存';
  if (code === 'C30_ZERO_SALE') return '淘汰候选复核';
  if (code === 'TRAFFIC_NO_SALE') return '优化转化';
  if (code === 'HIGH_EXPOSURE_LOW_CLICK') return '优化点击';
  if (code === 'HIGH_VISITOR_LOW_PAY') return '优化支付转化';
  if (code === 'SALE_DROP_7D' || code === 'EXPOSURE_DROP_7D') return '修复下滑';
  return '参考观察';
}
function prioritySort(row) {
  const p = row.priority || '';
  const base = p === '高' ? 10 : p === '中' ? 30 : 60;
  const codeRank = {
    WAIT_SHELF_BLOCKED: 1,
    COVERAGE_MISSING: 2,
    DISPLAY_STOCK_LOW: 3,
    TRAFFIC_NO_SALE: 4,
    HIGH_EXPOSURE_LOW_CLICK: 5,
    HIGH_VISITOR_LOW_PAY: 6,
    SALE_DROP_7D: 7,
    EXPOSURE_DROP_7D: 8,
    C30_ZERO_SALE: 9,
  }[row.ruleCode] || 90;
  return base + codeRank;
}
function oneLineAction(row) {
  const target = [row.storeKey, row.standardGoodsSn, row.skc].filter(Boolean).join(' / ');
  const category = actionCategory(row);
  if (row.ruleCode === 'WAIT_SHELF_BLOCKED') return `${category}：${target}`;
  if (row.ruleCode === 'COVERAGE_MISSING') return `补 1 条可上架链接：${target}`;
  if (row.ruleCode === 'DISPLAY_STOCK_LOW') return `把 SHEIN 展示库存调高：${target}`;
  if (row.ruleCode === 'C30_ZERO_SALE') return `30天无销量，复核是否替换/下架：${target}`;
  return `${category}：${target}`;
}
function includeInActionList(row, ctx) {
  const code = row.ruleCode || '';
  if (['SHEIN_FLOW_DIAGNOSE', 'HARD_DEAD_LINK', 'DUPLICATE_WEAK_LINK', 'DISPLAY_STOCK_LOW'].includes(code)) return false;
  if (row.allStoresNoOnShelfNoReminder || ctx.suppressedStandards.has(row.standardGoodsSn)) return false;

  const perf = actionPerf(row, ctx);
  const inv = actionInventory(row, ctx);
  const cov = actionCoverage(row, ctx);
  const stats = actionStandardStats(row, ctx);

  if (code === 'WAIT_SHELF_BLOCKED') return true;

  if (code === 'COVERAGE_MISSING') {
    return stats.onShelfStores.size > 0
      && (stats.c7SaleCnt >= 3 || stats.c30SaleCnt >= 10 || (stats.onShelfStores.size >= 5 && stats.c30SaleCnt >= 5));
  }

  if (code === 'DISPLAY_STOCK_LOW') {
    const recentSale = Math.max(metric(perf.c7SaleCnt, 0), metric(inv.c7dSaleCnt, 0));
    const stock = metric(inv.platformDisplayStock, Number.POSITIVE_INFINITY);
    const saleDays = metric(inv.minStockSaleDays, Number.POSITIVE_INFINITY);
    return recentSale >= 2 && (stock <= 10 || saleDays <= 2);
  }

  if (code === 'TRAFFIC_NO_SALE') {
    return metric(perf.c30SaleCnt, 0) === 0 && metric(perf.c30EpsUv, 0) >= 1000;
  }

  if (code === 'HIGH_EXPOSURE_LOW_CLICK') {
    return metric(perf.c7EpsUv, 0) >= 500 && metric(perf.c7ClickRate, 1) < 0.01;
  }

  if (code === 'HIGH_VISITOR_LOW_PAY') {
    return metric(perf.c7GoodsUv, 0) >= 100 && metric(perf.c7PayRate, 1) < 0.01;
  }

  if (code === 'SALE_DROP_7D') {
    return metric(perf.prev7SaleCnt, 0) >= 5 && metric(perf.c7SaleCnt, 0) <= metric(perf.prev7SaleCnt, 0) * 0.5;
  }

  if (code === 'EXPOSURE_DROP_7D') {
    return metric(perf.prev7EpsUv, 0) >= 500 && metric(perf.c7EpsUv, 0) <= metric(perf.prev7EpsUv, 0) * 0.5;
  }

  if (code === 'C30_ZERO_SALE') {
    return metric(perf.c30SaleCnt, 0) === 0 && metric(perf.c30EpsUv, 0) >= 500 && metric(cov.onShelfCount, 0) > 1;
  }

  return false;
}

function actionSeverity(row, ctx) {
  const perf = actionPerf(row, ctx);
  const inv = actionInventory(row, ctx);
  const stats = actionStandardStats(row, ctx);
  if (row.ruleCode === 'WAIT_SHELF_BLOCKED') return 100000;
  if (row.ruleCode === 'COVERAGE_MISSING') return stats.c30SaleCnt * 100 + stats.c7SaleCnt * 20 + stats.onShelfStores.size;
  if (row.ruleCode === 'DISPLAY_STOCK_LOW') return Math.max(metric(perf.c7SaleCnt, 0), metric(inv.c7dSaleCnt, 0)) * 100 - metric(inv.platformDisplayStock, 0);
  if (row.ruleCode === 'TRAFFIC_NO_SALE') return metric(perf.c30EpsUv, 0);
  if (row.ruleCode === 'HIGH_EXPOSURE_LOW_CLICK') return metric(perf.c7EpsUv, 0);
  if (row.ruleCode === 'HIGH_VISITOR_LOW_PAY') return metric(perf.c7GoodsUv, 0);
  if (row.ruleCode === 'SALE_DROP_7D') return metric(perf.prev7SaleCnt, 0) - metric(perf.c7SaleCnt, 0);
  if (row.ruleCode === 'EXPOSURE_DROP_7D') return metric(perf.prev7EpsUv, 0) - metric(perf.c7EpsUv, 0);
  if (row.ruleCode === 'C30_ZERO_SALE') return metric(perf.c30EpsUv, 0);
  return 0;
}

function compareActionSuggestions(a, b, ctx) {
  return prioritySort(a) - prioritySort(b)
    || actionSeverity(b, ctx) - actionSeverity(a, ctx)
    || String(a.storeKey || '').localeCompare(String(b.storeKey || ''))
    || String(a.standardGoodsSn || '').localeCompare(String(b.standardGoodsSn || ''), 'zh-Hans-CN')
    || String(a.skc || '').localeCompare(String(b.skc || ''));
}

function capStoreActions(rows, maxActionsPerStore = 0) {
  if (!maxActionsPerStore || maxActionsPerStore <= 0) return rows;
  return rows.slice(0, maxActionsPerStore);
}

function markDailyFocus(rows, maxFocusPerStore = 3) {
  rows.forEach((row, index) => {
    row['是否今日重点'] = index < maxFocusPerStore;
  });
  return rows;
}
function actionRecord(row, fetchTime) {
  const sort = prioritySort(row);
  return {
    '唯一键': row.uniqueKey,
    '日期': row.date,
    '今日排序': sort,
    '处理状态': '待处理',
    '是否纳入今日清单': true,
    '是否今日重点': row.priority === '高',
    '实操规则版本': 'v2-strict-2026-05-01',
    '优先级': row.priority,
    '操作分类': actionCategory(row),
    '一句话动作': oneLineAction(row),
    '店铺代号': row.storeKey,
    '分组': row.groupKey,
    '店铺名称': row.shopName,
    '标准货号': row.standardGoodsSn,
    'SKC': row.skc || '—（补链看货号）',
    '目标类型': row.targetType,
    '目标键': row.targetKey,
    '原始建议类型': row.suggestionType,
    '规则代码': row.ruleCode,
    '为什么': row.reason,
    '证据': row.evidence,
    '建议动作': row.action,
    '最近抓取时间': dateTime(fetchTime),
  };
}
function applyAllStoreNoOnShelfSuppression(objects, enabled = new Set()) {
  const selected = new Set(objects.map(x => x.obj?.store?.storeKey).filter(Boolean));
  const isFullAllStoreBatch = enabled.size > 0 && [...enabled].every(key => selected.has(key));
  if (!isFullAllStoreBatch) return new Set();
  const stats = new Map();
  for (const {obj} of objects) {
    for (const row of obj.coverageRows || []) {
      if (!row.standardGoodsSn) continue;
      const item = stats.get(row.standardGoodsSn) || {stores: new Set(), onShelfStores: new Set()};
      item.stores.add(obj.store?.storeKey || row.storeKey);
      if (row.hasOnShelfLink) item.onShelfStores.add(obj.store?.storeKey || row.storeKey);
      stats.set(row.standardGoodsSn, item);
    }
  }
  const suppressed = new Set();
  for (const [standardGoodsSn, item] of stats.entries()) {
    if (item.stores.size >= enabled.size && item.onShelfStores.size === 0) suppressed.add(standardGoodsSn);
  }
  if (!suppressed.size) return suppressed;
  for (const {obj} of objects) {
    for (const row of obj.coverageRows || []) {
      if (!suppressed.has(row.standardGoodsSn)) continue;
      row.allStoresNoOnShelfNoReminder = true;
      row.needSupplementLink = false;
      row.recommendation = '全部店均无上架链接，按暂不上/库存未到处理，暂不提醒';
      if (!String(row.coverageStatus || '').includes('暂不提醒')) row.coverageStatus = `${row.coverageStatus}（全部店均无上架，暂不提醒）`;
    }
    obj.suggestionRows = (obj.suggestionRows || []).filter(row => !(row.ruleCode === 'COVERAGE_MISSING' && suppressed.has(row.standardGoodsSn)));
  }
  return suppressed;
}
async function ensureActionViews(baseToken, actionTableId, date) {
  const storesCfg = JSON.parse(await fs.readFile(STORES_PATH, 'utf8'));
  const enabledStores = (storesCfg.stores || []).filter(s => s.enabled !== false);
  const visibleFields = [
    '今日排序',
    'SKC',
    '店铺代号',
    '处理状态',
    '是否今日重点',
    '优先级',
    '操作分类',
    '一句话动作',
    '标准货号',
    '为什么',
    '证据',
    '建议动作',
    '实操规则版本',
    '最近抓取时间',
  ];
  const sort = [{field: '今日排序', desc: false}, {field: '店铺代号', desc: false}];
  const configs = [
    {
      name: '今日重点',
      filter: {logic: 'and', conditions: [['日期', '==', `ExactDate(${date})`], ['处理状态', '==', '待处理'], ['是否纳入今日清单', '==', true], ['是否今日重点', '==', true]]},
    },
    {
      name: '全部待处理',
      filter: {logic: 'and', conditions: [['日期', '==', `ExactDate(${date})`], ['处理状态', '==', '待处理'], ['是否纳入今日清单', '==', true]]},
    },
    ...enabledStores.map(store => ({
      name: `${store.storeKey}店今日实操`,
      filter: {logic: 'and', conditions: [['日期', '==', `ExactDate(${date})`], ['处理状态', '==', '待处理'], ['是否纳入今日清单', '==', true], ['店铺代号', '==', store.storeKey]]},
    })),
  ];
  const views = await listViews(baseToken, actionTableId);
  const byName = new Map(views.map(v => [v.name, v]));
  const results = [];
  for (const cfg of configs) {
    let view = byName.get(cfg.name);
    if (!view) view = await createView(baseToken, actionTableId, cfg.name, 'grid');
    const viewId = resolveViewId(view);
    if (!viewId) throw new Error(`Cannot resolve view id for ${cfg.name}`);
    await runLark(['base', '+view-set-filter', '--as', 'user', '--base-token', baseToken, '--table-id', actionTableId, '--view-id', viewId], `view-filter-${cfg.name}`, cfg.filter);
    await runLark(['base', '+view-set-sort', '--as', 'user', '--base-token', baseToken, '--table-id', actionTableId, '--view-id', viewId], `view-sort-${cfg.name}`, {sort_config: sort});
    await runLark(['base', '+view-set-visible-fields', '--as', 'user', '--base-token', baseToken, '--table-id', actionTableId, '--view-id', viewId], `view-fields-${cfg.name}`, {visible_fields: visibleFields});
    results.push({name: cfg.name, viewId});
  }
  return results;
}

async function resolveInputFiles(args) {
  if (args.files?.length) return args.files;
  const storesCfg = JSON.parse(await fs.readFile(STORES_PATH, 'utf8'));
  const enabled = new Set((storesCfg.stores || []).filter(s => s.enabled !== false).map(s => s.storeKey));
  let storeKeys = args.stores?.length ? args.stores : (storesCfg.groups?.[args.group] || []);
  if (args.group === 'ALL' && (!storeKeys || !storeKeys.length)) storeKeys = [...enabled];
  storeKeys = [...new Set(storeKeys.map(s => String(s || '').trim().toUpperCase()).filter(s => enabled.has(s)))];
  const files = storeKeys.map(storeKey => path.join(LINK_DIR, storeKey, `${args.date}.json`));
  const existing = [];
  const missing = [];
  for (const file of files) {
    if (await fileExists(file)) existing.push(file);
    else missing.push(path.relative(ROOT, file));
  }
  if (!existing.length) throw new Error(`No link fetch files found for ${args.date || ''}; missing examples: ${missing.slice(0, 5).join(', ')}`);
  if (missing.length) console.warn(`[sync] link input missing ${missing.length} files, examples: ${missing.slice(0, 5).join(', ')}`);
  return existing;
}

async function main() {
  const args = parseArgs(process.argv.slice(2));
  const state = await readJson(STATE_PATH);
  const baseToken = state.baseToken;
  if (!baseToken) throw new Error(`Missing baseToken in ${STATE_PATH}`);
  const tableIds = await ensureAllTables(baseToken, state);
  await saveState(state);
  if (args.ensureOnly) {
    console.log(JSON.stringify({ok: true, ensuredTables: tableIds}, null, 2));
    return;
  }
  if (args.viewsOnly) {
    const actionViews = await ensureActionViews(baseToken, tableIds[TABLES.actionList], args.date);
    console.log(JSON.stringify({ok: true, date: args.date, actionViews, ensuredTables: tableIds}, null, 2));
    return;
  }

  const files = await resolveInputFiles(args);
  const objects = [];
  for (const file of files) {
    try {
      objects.push({file, obj: await readJson(file)});
    } catch (err) {
      throw new Error(`Cannot read link fetch file ${file}: ${err.message}`);
    }
  }
  const fetchTime = objects.map(x => x.obj.fetchTime).filter(Boolean).sort().at(-1) || new Date().toISOString().slice(0, 16).replace('T', ' ');
  const date = args.date || objects[0]?.obj?.date;
  const storesCfg = JSON.parse(await fs.readFile(STORES_PATH, 'utf8'));
  const enabledStores = new Set((storesCfg.stores || []).filter(s => s.enabled !== false).map(s => s.storeKey));
  const globallySuppressedStandards = applyAllStoreNoOnShelfSuppression(objects, enabledStores);
  normalizeSuggestionRows(objects, globallySuppressedStandards);
  const actionContext = buildActionContext(objects, globallySuppressedStandards);
  const linkRows = [];
  const perfRows = [];
  const invRows = [];
  const covRows = [];
  const sugRows = [];
  const actionRows = [];
  for (const {obj} of objects) {
    const storeActionRows = markDailyFocus(
      capStoreActions(
        (obj.suggestionRows || [])
          .filter(r => includeInActionList(r, actionContext))
          .sort((a, b) => compareActionSuggestions(a, b, actionContext))
          .map(r => actionRecord(r, obj.fetchTime)),
        args.maxActionsPerStore
      )
    );
    linkRows.push(...(obj.linkRows || []).map(r => linkRecord(r, obj.fetchTime)));
    perfRows.push(...(obj.performanceRows || []).map(r => performanceRecord(r, obj.fetchTime)));
    invRows.push(...(obj.inventoryRows || []).map(r => inventoryRecord(r, obj.fetchTime)));
    covRows.push(...(obj.coverageRows || []).map(r => coverageRecord(r, obj.fetchTime)));
    sugRows.push(...(obj.suggestionRows || []).map(r => suggestionRecord(r, obj.fetchTime)));
    actionRows.push(...storeActionRows);
  }

  const syncResults = {};
  const selectedStorePrefixes = [...new Set(objects.map(x => x.obj.store?.storeKey).filter(Boolean))].map(storeKey => `${date}__${storeKey}__`);
  if (!args.actionsOnly && !args.suggestionsOnly) {
    syncResults[TABLES.linkMain] = await upsertRecords(baseToken, tableIds[TABLES.linkMain], linkRows, 'link-main', {skipUpdates: args.skipLinkMainUpdates});
    syncResults[TABLES.performance] = await upsertRecords(baseToken, tableIds[TABLES.performance], perfRows, 'link-performance');
    syncResults[TABLES.inventory] = await upsertRecords(baseToken, tableIds[TABLES.inventory], invRows, 'link-inventory');
    syncResults[TABLES.coverage] = await upsertRecords(baseToken, tableIds[TABLES.coverage], covRows, 'link-coverage');
  } else {
    syncResults.facts = {skipped: true, reason: args.suggestionsOnly ? 'suggestions-only' : 'actions-only'};
  }
  if (!args.actionsOnly) {
    syncResults[TABLES.suggestion] = await upsertRecords(baseToken, tableIds[TABLES.suggestion], sugRows, 'link-suggestion', {skipUpdates: true, deleteStalePrefixes: selectedStorePrefixes});
  }
  let actionViews = null;
  if (!args.suggestionsOnly) {
    syncResults[TABLES.actionList] = await upsertRecords(
      baseToken,
      tableIds[TABLES.actionList],
      actionRows,
      'link-action-list',
      args.hideStaleActions ? {} : {deleteStalePrefixes: selectedStorePrefixes}
    );
    actionViews = await ensureActionViews(baseToken, tableIds[TABLES.actionList], date);
  }
  let dashboard = null;
  if (args.setupDashboard) throw new Error('Link Base Dashboard is retired. Use outputs/link-dashboard/index.html instead.');

  const summary = {
    ok: true,
    date,
    files,
    counts: {
      linkRows: linkRows.length,
      performanceRows: perfRows.length,
      inventoryRows: invRows.length,
      coverageRows: covRows.length,
      suggestionRows: sugRows.length,
      actionRows: actionRows.length,
      globallySuppressedStandards: globallySuppressedStandards.size,
    },
    tables: tableIds,
    actionViews,
  };
  console.log(JSON.stringify(summary, null, 2));
}

await main();
