#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
import {addDays, buildContext, firstDayOfPrevMonth} from './fetch_et_forwarder.mjs';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = relative => fs.readFileSync(path.join(root, relative), 'utf8');
const fetcher = read('scripts/fetch_et_forwarder.mjs');
const sync = read('scripts/cloud_et_storage_fee_sync.sh');
const service = read('infra/systemd/shein-bi-cloud-et-storage-fee.service');
const timer = read('infra/systemd/shein-bi-cloud-et-storage-fee.timer');

assert.match(fetcher, /sort:\s*ctx\.storageFeeOnly\s*\?\s*2\s*:\s*''/, 'storage-fee-only must request IncomeBill sort=2');
assert.match(fetcher, /if \(args\.storageFeeOnly\) keys = \['income_bill'\]/, 'storage-fee-only must not include generic finance endpoints');
assert.equal(addDays('2026-07-19', -2), '2026-07-17', 'Beijing calendar overlap must not shift back one day');
assert.equal(addDays('2026-03-01', -1), '2026-02-28', 'calendar arithmetic must cross month boundaries');
assert.equal(firstDayOfPrevMonth('2026-07-19'), '2026-06-01', 'previous finance month must begin on its Beijing first day');
assert.equal(firstDayOfPrevMonth('2026-01-19'), '2025-12-01', 'previous finance month must cross year boundaries');
assert.match(fetcher, /Date\.UTC\(year, month - 1, day \+ Number\(offset\)\)/, 'date helper must use timezone-independent calendar arithmetic');
const dailyContext = buildContext({mode: 'daily', date: '2026-07-19', startDate: '2025-11-17', shipLookbackDays: 7, limit: 100, storageFeeOnly: true});
assert.equal(dailyContext.rollingStart, '2026-07-17', 'daily context must use the intended two-day Beijing overlap');
assert.equal(dailyContext.financeStart, '2026-06-01', 'daily finance context must start on the prior month first day');
assert.match(sync, /--storage-fee-only/, 'dedicated sync must use the storage-fee-only fetch contract');
assert.match(sync, /ET_TRANSPORT="\$\{SHEIN_ET_TRANSPORT:-http\}"/, 'dedicated sync must use direct HTTP by default');
assert.match(sync, /--transport "\$ET_TRANSPORT"/, 'dedicated sync must pass the selected ET transport');
assert.match(sync, /--session-file "\$ET_HTTP_SESSION_FILE"/, 'dedicated sync must reuse the protected ET HTTP cookie jar');
assert.match(sync, /et_storage_fee_http_session\.local\.json/,
  'the sheinops storage-fee service must not share a root-owned 0600 cookie file');
assert.match(sync, /shein-bi-cloud-et-forwarder\.lock/, 'dedicated sync must share the generic ET lock');
assert.match(sync, /flock -w "\$\{SHEIN_ET_STORAGE_FEE_LOCK_WAIT_SEC:-1800\}" 9/, 'dedicated sync must wait up to 30 minutes for the shared ET lock');
assert.match(sync, /failed phase=lock/, 'shared-lock exhaustion must raise an explicit alert');
assert.match(sync, /exit 75/, 'shared-lock exhaustion must return nonzero');
assert.doesNotMatch(sync, /flock -n 9[\s\S]*generic ET sync holds lock; skip/, 'shared-lock contention must not be silently skipped');
assert.match(sync, /et_storage_fee_sync_state\.json/, 'dedicated sync must keep state separate from generic ET sync');
assert.match(sync, /outputs\/et-storage-fee/, 'dedicated sync must keep output separate from the root-owned generic ET output tree');
assert.match(sync, /--out-dir "\$OUTPUT_DIR"/, 'dedicated sync must pass its isolated output directory to the fetcher');
assert.doesNotMatch(sync, /outputs\/et-forwarder\/latest-manifest\.json/, 'dedicated sync must not read the generic ET latest-manifest pointer');
assert.match(sync, /export SHEIN_DOCKER_USE_SUDO="\$\{SHEIN_DOCKER_USE_SUDO:-1\}"/, 'manual backfills must use the audited Docker sudo path');
assert.match(sync, /daily\|backfill/, 'dedicated sync must expose daily and explicit backfill modes');
assert.match(sync, /2025-11-17/, 'backfill must start at the approved storage-fee boundary');
assert.match(sync, /--detail-all/, 'daily and backfill paths must download storage-fee detail exports');
assert.match(sync, /--detail-names storage_fee_product_detail/, 'storage-fee sync must skip generic income_bill_item detail requests');
assert.match(sync, /ET_CHROME_TMP_DIR=.*shein-bi-et-storage-fee-chrome-tmp/, 'storage-fee sync must use a dedicated Chrome TMPDIR');
assert.match(sync, /export TMPDIR="\$ET_CHROME_TMP_DIR"/, 'dedicated Chrome TMPDIR must be exported to the fetcher');
assert.match(sync, /--user-data-dir=\$ET_PROFILE_DIR/, 'cleanup must target Chrome by its exact ET profile argument');
assert.match(sync, /index\(\$0, profile\) \{print \$1\}/, 'cleanup must first select PIDs by the exact ET profile argument');
assert.match(sync, /\/proc\/\$pid\/exe/, 'cleanup must verify each candidate executable through procfs');
assert.match(sync, /basename -- "\$exe"/, 'cleanup must support Chrome launched from an absolute executable path');
assert.match(sync, /chrome\|google-chrome\|google-chrome-stable\|chromium\|chromium-browser/, 'cleanup must whitelist real Chrome executable basenames');
assert.doesNotMatch(sync, /\(\^\|\[\[:space:\]\]\)\(google-chrome/, 'cleanup must not require a bare Chrome command name in ps output');
assert.match(sync, /signal_et_chrome TERM[\s\S]*signal_et_chrome KILL/, 'ET Chrome cleanup must escalate TERM to KILL');
assert.match(sync, /trap cleanup_et_browser EXIT/, 'ET Chrome cleanup must run on success and failure');
assert.doesNotMatch(sync, /find \/tmp -maxdepth/, 'dedicated cleanup must not sweep global tmp files');
assert.match(sync, /incomplete ExportStoreFee detail; retry required/, 'partial ExportStoreFee detail must fail loudly for retry');
assert.match(sync, /load_et_forwarder_warehouse\.mjs[\s\S]*refresh_profit_marts\.sh[\s\S]*enqueue_bi_portal_sections\.sh/, 'warehouse load, profit refresh, and deferred Portal enqueue must be ordered');
assert.match(sync, /refresh_profit_marts\.sh[\s\S]*check_storage_fee_profit\.mjs[\s\S]*audit_bi_warehouse\.mjs/, 'coverage and warehouse audit must run after profit refresh');
assert.match(sync, /--sections profit,homeProfit/, 'storage sync must queue only the profit sections it changes');
assert.match(sync, /--priority 10/, 'settled storage-fee profit refresh must retain business priority');
assert.doesNotMatch(sync, /prewarm_bi_portal_sections\.sh/, 'storage settlement must not synchronously wait for Portal materialization');
assert.doesNotMatch(sync, /--sections [^\n]*inventoryTrend/, 'storage sync must not trigger unrelated inventory trend generation');
assert.match(sync, /PHASE="fetch"/, 'sync must initialize an explicit failure phase');
for (const phase of ['fetch', 'validate', 'load', 'refresh', 'audit', 'enqueue']) {
  assert.match(sync, new RegExp(`PHASE="${phase}"`), `sync must track ${phase} failures`);
}
assert.match(sync, /phase=\$PHASE/, 'failure alert must report the current phase');
assert.match(sync, /PHASE" == "fetch"[\s\S]*PHASE" == "validate"[\s\S]*PHASE" == "load"/, 'only pre-refresh phases may promise old caches were retained');
assert.match(sync, /raw\/cache may have advanced; inspect audit/, 'post-refresh failures must not claim old caches were retained');
assert.doesNotMatch(sync, /\/Finance\/(?:IncomeBill\/)?(?:Create|Update|Delete|Submit)/i, 'dedicated sync must not add ET write endpoints');
assert.match(service, /cloud_et_storage_fee_sync\.sh daily/, 'service must run daily mode');
assert.match(service, /^Environment=SHEIN_ET_TRANSPORT=http$/m, 'normal storage-fee runs must not launch Chrome');
assert.match(service, /et_storage_fee_http_session\.local\.json/);
assert.doesNotMatch(service, /run_host_browser_read_job\.sh|--class browser/, 'storage-fee must not reserve a browser lane');
assert.match(service, /^User=sheinops$/m, 'service must run as sheinops');
assert.match(service, /^Group=sheinops$/m, 'service must use the sheinops group');
assert.match(service, /^UMask=0027$/m, 'service must create non-world-readable files');
assert.match(service, /^Environment=HOME=\/home\/sheinops$/m, 'service must not use root HOME with a sheinops profile');
assert.match(service, /^ProtectSystem=full$/m, 'service must protect system paths');
assert.match(service, /^ProtectKernelTunables=true$/m, 'service must protect kernel tunables');
assert.match(service, /^LockPersonality=true$/m, 'service must lock execution personality');
assert.doesNotMatch(service, /^NoNewPrivileges=true$/m, 'service must allow documented NOPASSWD sudo operations');
assert.doesNotMatch(service, /^RestrictSUIDSGID=true$/m, 'service must not block sudo elevation');
assert.match(service, /shein-bi-cloud-et-forwarder\.lock/, 'service must share the generic ET lock');
assert.match(service, /et_storage_fee_sync_state\.json/, 'service must configure the isolated storage-fee state file');
assert.match(service, /outputs\/et-storage-fee/, 'service must configure the isolated storage-fee output directory');
assert.match(service, /^Environment=SHEIN_DOCKER_USE_SUDO=1$/m, 'service must explicitly enable the audited Docker sudo path');
assert.match(timer, /14:20:00 Asia\/Shanghai/, 'timer must use the bounded 14:20-14:27 host-heavy slot');
assert.match(timer, /Persistent=false/, 'a missed run must not replay inside the reserved home lane');
assert.doesNotMatch(timer, /01,03|\*\/2|every two hours/i, 'timer must not run every two hours');

console.log('ET storage-fee sync contract: ok');
